### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [klassm/andFHEM#1013]
Matthias, would you consider publishing the `.apk` file here with your Github project – preferably on the [releases/](https://github.com/klassm/andFHEM/releases) page? The only release (code) attached there is a bit outdated, but adding fresh releases shouldn't be too hard. Big advantage over that APK-Link from the project site: one can see the date and tell whether the `.apk` was updated. Plus I could automatically grab updates and put them into [my repo](https://android.izzysoft.de/repo), where they'd be available for other Google-resisters using the F-Droid client with automatic update information :)

Thanks in advance!

**Comment by klassm** [comment]
New versions will be automatically published on GitHub (non premium only)

Matthias

**Comment by IzzySoft** [comment]
Cool – thanks! And yes, of course only the non-premium variant :) Just for clarification: Those end up on the `releases/` page then? b166a46 suggests as much, but I'm not that fit in Gradle to tell for sure :)

**Comment by klassm** [comment]
Yes: https://github.com/klassm/andFHEM/releases

**Comment by IzzySoft** [comment]
Superb! Looking forward to that. PS: The last version listed on F-Droid is v2.4.1 (2013-07-11) – while on Play it's 4.0.4 (04/2016). Am I interpreting that correctly that F-Droid won't list newer releases anymore?

**Comment by klassm** [comment]
I suppose. I've never done anything to be listed on F-Droid. Thus, I have no idea who once took care of releasing the apk there.

**Comment by IzzySoft** [comment]
OK, thanks! Then as soon as the next release is out (and has its `.apk` attached here), it will be available via my repo. I hope I see that in time than, as for the initial listing in the repo I need an `.apk` being available (and currently there is none). Ah, wait, I can take the latest from my device "for initialization": So [here it is](https://android.izzysoft.de/repo/apk/li.klass.fhem). Updates will be pulled automatically within 24h usually.

Thanks a lot again! And feel free to point those "Google refusers" (like me) to get the app from there :)

**Comment by IzzySoft** [comment]
@klassm I've noticed that for quite a while there are no more APKs attached to the releases. Is there any reason? Notice that my auto-updater doesn't find them if you hide them inside some ZIP :wink:

**Comment by klassm** [comment]
Hm I guess this changed with some Android SDK update. I'll look into this.

Am 07.12.2017 21:16 schrieb "Izzy" <notifications@github.com>:

@klassm <https://github.com/klassm> I've noticed that for quite a while
there are no more APKs attached to the releases. Is there any reason?
Notice that my auto-updater doesn't find them if you hide them inside some
ZIP 😉

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/klassm/andFHEM/issues/1013#issuecomment-350081955>, or mute
the thread

**Comment by IzzySoft** [comment]
Thanks a lot! For the next version is sufficient. For the current one I've just done the update manually.
