### ISSUE TITLE
Dimming - only "Dim +" and "Dim -" shown and not working

### ISSUE THREAD

**Issue by greg4b** [klassm/andFHEM#1016]
I'm complaining that in this release only the DIM+ and DIM- buttons are present of a milight LED bulb (The other buttons (webCmd on:off:dim:hue:night:rgb ffffff:rgb ff0000:rgb 00ff00:rgb 0000ff:rgb ffff00, color picker) disappeared).

Device is 10" tablet - no matter upright or landscape mode. On 5" Sony Xperia Z the buttons are shown...

Further the Dim+ and Dim- buttons are not working since the previour release.

Also the slider does not correspond to the actual state of the LED - slider jumps after moving (and setting the light) to the left side (zero).

Thanks,

Gregor

**Comment by klassm** [comment]
Hi,

well this is difficult to tell - andFHEM will now refresh the device state after each command. Thus, after switching, you will see the state that corresponds to the FHEMWEB interface. Without being able to see what the device state is _after_ switching, we won't find the reason for your jumping sliders.

Supposedly, the issue for the non working dim+ and dim- buttons is exactly the same one.

Trying a MiLight device in my own FHEM instance, I can see both webcmd buttons as well as the color picker button.
(define d MilightDevice RGB  mat_halogen 0)

Matthias

**Comment by klassm** [comment]
No comment since may => close.
