### ISSUE TITLE
graph empty/leer (svg dblog)

### ISSUE THREAD

**Issue by ManOki** [klassm/andFHEM#1023]
alle svg plots sind bei mir leer. die fehlermeldung dahinter kann ich nicht vollständig lesen. die informationen kommen aus einem dblog.

<img src="https://cloud.githubusercontent.com/assets/1769457/16492674/e079c6da-3ee2-11e6-8e3f-eb8e1d642a1a.png" height="512">

<img src="https://cloud.githubusercontent.com/assets/1769457/16492675/e09a59d6-3ee2-11e6-8349-7a5cbc18254a.png" width="512">

**Comment by klassm** [comment]
Hi,

kannst du bitte bei Gelegenheit das Problem reproduzieren und anschließend das andFHEM Log anhängen bzw. schicken? In den Einstellungen gibt es einen Knopf um das Log an andFHEM@klass.li zu schicken. Dort sieht man zumindest das Kommando, das für das Auslesen der Logs geschickt wurde. Vielleicht sieht man dann warum es nicht funktioniert.

Matthias

**Comment by ManOki** [comment]
Hier ist das Logfile.

Device information:
OS-Version: 3.4.0-g9f1ae62
API-Level: 23
Device: htc_m8
Manufacturer: htc
Model: m8
Product: cm_m8
App-version: 4.0.9

[andFHEM--1750050094.log.txt](https://github.com/klassm/andFHEM/files/345969/andFHEM--1750050094.log.txt)

**Comment by klassm** [comment]
Hi,
hast du den Graph kurz vor dem Ziehen des Logs denn aufgerufen? Ich vermisse gerade das Kommando zum Laden der Log Einträge im Log...
Matthias

**Comment by ManOki** [comment]
Zeile 333: `07-04 10:59:40.165 17697 17902 D li.klass.fhem.service.intent.DeviceIntentService: li.klass.fhem.constants.Actions.DEVICE_GRAPH`

Nicht das Richtige?

Mein Vorgehen war folgendermaßen: Ich habe aus den Favoriten auf ein Device geklickt und dann im Bereich Graphen einen beliebigen ausgewählt. (Dabei scheint es unabhängig zu sein, welches Device man auswählt, es werden immer alle verfügbaren Graphen zur Auswahl angezeigt.) Anschließend bin ich über den Zurück-Button und den Menü-Button in die Einstellungen gegangen. Dort habe ich unter Fehlerbehandlung den Punkt "Protokoll senden" ausgewählt.

**Comment by klassm** [comment]
Hm, soweit hast du natürlich recht. Es wird versucht Graph-Daten zu laden, allerdings kommt er nie bei dem Kommando an. Ich habe jetzt mal an einer Stelle mehr Logging eingebaut und eine etwas seltsame Vorbedingung rausgenommen. Vielleicht kannst du die neue Version nochmal ausprobieren und ggf. dann nochmal ein neues Log ziehen.
Matthias

**Comment by ManOki** [comment]
Hier ist mein neues Log. Der Graph wird immer noch nicht angezeigt. Ich vermute den Fehler irgendwo dort:
`07-17 18:30:30.157 19438 19438 W View    : requestLayout() improperly called by android.widget.TableLayout`

(Leider geht grad github upload nicht, daher: http://pastebin.com/YjrYdYE6 )

**Comment by klassm** [comment]
Hi,

hm nein eher nicht. Das Problem ist die Log Ausgabe:

`GraphService: getGraphData - getting graph data for device MyPC and 0 series`

Damit werden schlicht keine Daten geholt und der Graph bleibt leer. Kannst du mir bitte mal das zugehörige gplot-File schicken? Eventuell ist einfach im GPlot Parser etwas schief.

Matthias

**Comment by ManOki** [comment]
Das GPlot-File lautet:
```
# Created by FHEM/98_SVG.pm, 2016-04-22 17:00:17
set terminal png transparent size <SIZE> crop
set output '<OUT>.png'
set xdata time
set timefmt "%Y-%m-%d_%H:%M:%S"
set xlabel " "
set title 'Anwesenheit'
set ytics 
set y2tics 
set grid
set ylabel "Anwesenheit"
set y2label "Tür/Fenster"
set yrange [0:100]
set y2range [0:1]

#logdb Handy1:state:::$val=($val=~'present'?50:0)
#logdb Handy2:state:::$val=($val=~'present'?50:0)
#logdb whg_tuer:onoff
#logdb k_fenster:opened:::$val=($val=~'opened'?1:0)
#logdb sz_fenster:opened:::$val=($val=~'opened'?1:0)

plot "<IN>" using 1:2 axes x1y1 title 'Handy1' ls l1fill lw 1.5 with steps,\
     "<IN>" using 1:2 axes x1y1 title 'Handy2' ls l3fill lw 1.5 with steps,\
     "<IN>" using 1:2 axes x1y2 title 'Tür' ls l2 lw 2 with steps,\
     "<IN>" using 1:2 axes x1y2 title 'Fenster Küche' ls l0 lw 1 with points,\
     "<IN>" using 1:2 axes x1y2 title 'Fenster Schlafzimmer' ls l5 lw 1 with points
```
Und das dazu passende "Preprocessed Data" direkt aus Fhem:
```
get logdb HISTORY INT 2016-08-02_00:00:00 2016-08-03_00:00:01 Handy1:state:::$val=($val=~'present'?50:0) Handy2:state:::$val=($val=~'present'?50:0) whg_tuer:onoff k_fenster:opened:::$val=($val=~'opened'?1:0) sz_fenster:opened:::$val=($val=~'opened'?1:0)

2016-08-02_03:55:41 50
2016-08-02_07:55:42 50
2016-08-02_10:28:43 0
2016-08-02_10:30:43 50
2016-08-02_11:25:43 0
2016-08-02_15:25:45 0
#Handy1:state:::$val=($val=~'present'?50:0)
2016-08-02_03:43:41 50
2016-08-02_07:43:42 50
2016-08-02_11:36:44 0
2016-08-02_11:37:45 50
2016-08-02_15:37:47 50
#Handy2:state:::$val=($val=~'present'?50:0)
2016-08-02_10:32:47 1
2016-08-02_10:33:15 0
2016-08-02_10:37:45 1
2016-08-02_10:37:51 0
2016-08-02_11:18:23 1
2016-08-02_11:18:39 0
#whg_tuer:onoff:::
2016-08-02_10:04:28 0
#k_fenster:opened:::$val=($val=~'opened'?1:0)
#sz_fenster:opened:::$val=($val=~'opened'?1:0)
```

**Comment by klassm** [comment]
Hi,

Ok, der GPlot Parser ist es auch nicht. Allerdings finde ich in deinem geposteten Log auch nirgends einen Eintrag, dass er überhaupt versucht hat die Datei zu parsen. Wie heißt denn das GPlot File?

Im Log finde ich gerade:
``https://MYHOST/fhem/gplot/Anwesenheit.gplot
https://MYHOST/fhem/gplot/Anwesenheit_PC.gplot
https://MYHOST/fhem/gplot/SVG_Mebus_48.gplot
https://MYHOST/fhem/gplot/USV.gplot
https://MYHOST/fhem/gplot/az_heizung_plot.gplot
https://MYHOST/fhem/gplot/bad_heizung_plot.gplot
https://MYHOST/fhem/gplot/k_heizung_plot.gplot
https://MYHOST/fhem/gplot/sz_heizung_plot.gplot
https://MYHOST/fhem/gplot/wz_heizung_links_plot.gplot
https://MYHOST/fhem/gplot/wz_heizung_rechts_plot.gplot``

Ist die richtige Datei überhaupt dabei?

Wenn die Datei nicht dabei ist - kannst du dann bitte noch eine xmllist anhängen? Jetzt geht es in Bereiche bei denen wohl der Parser irgendetwas seltsames macht. Ohne die Eingabedaten wird das vermutlich recht schwierig zu finden.

Viele Grüße,
Matthias

**Comment by ManOki** [comment]
Ok, liegt es möglicherweise daran, dass ich configdb benutze und meine GPlot Dateien in meiner Datenbank liegen?

Ich habe die URL `https://MYHOST/fhem/gplot/Anwesenheit.gplot` mal ausprobiert und bekomme von FHEM nur die Startseite als HTML zurück.

[FHEM reference](http://fhem.de/commandref.html#configdb)
[FHEMWiki](http://www.fhemwiki.de/wiki/Configdb)

**Comment by klassm** [comment]
Das ist tatsächlich sehr wahrscheinlich, ja. Sieht man in der Definition des DbLog denn ob ConfigDB denn verwendet wird? Vielleicht kannst du wirklich mal eine xmllist des DbLog posten.

Was passiert denn wenn du 
configdb fileshow $$dein_gplot$$
absetzt?

**Comment by ManOki** [comment]
Ich vermute auch, das Problem ist, dass das Mapping zwischen `xmllist` und `configdb` ist.

Hier ist ein Auszug meiner `xmllist`:
```
		<DbLog name="logdb" state="connected" sets="reduceLog reopen:noArg rereadcfg:noArg count:noArg deleteOldDays userCommand" attrs="verbose:0,1,2,3,4,5 room group comment:textField-long alias eventMap userReadings:textField-long disable:0,1 DbLogType:Current,History,Current/History shutdownWait suppressUndef:0,1 DbLogSelectionMode:Exclude,Include,Exclude/Include DbLogExclude DbLogInclude cmdIcon devStateIcon devStateStyle icon sortby webCmd widgetOverride userattr"> 
			<INT key="CFGFN" value=""/> 
			<INT key="CONFIGURATION" value="./configDB.conf"/> 
			<INT key="DBMODEL" value="MYSQL"/> 
			<INT key="DEF" value="./configDB.conf .*:.*"/> 
			<INT key="NAME" value="logdb"/> 
			<INT key="NR" value="88"/> 
			<INT key="NTFY_ORDER" value="50-logdb"/> 
			<INT key="PID" value="29003"/> 
			<INT key="REGEXP" value=".*:.*"/> 
			<INT key="STATE" value="connected"/> 
			<INT key="TYPE" value="DbLog"/> 
			<INT key="dbconn" value="mysql:database=fhem;host=localhost;port=3306"/> 
			<INT key="dbuser" value="fhem"/> 
			<ATTR key="DbLogExclude" value=".*"/> 
			<ATTR key="DbLogSelectionMode" value="Exclude/Include"/> 
			<ATTR key="room" value="hidden"/> 
			<STATE key="countCurrent" value="1459" measured="2016-05-24 17:32:45"/> 
			<STATE key="countHistory" value="460161" measured="2016-05-24 17:32:45"/> 
			<STATE key="lastRowsDeleted" value="0E0" measured="2016-04-18 00:00:00"/> 
			<STATE key="state" value="connected" measured="2016-08-09 11:00:17"/> 
		</DbLog> 
[...]
		<SVG name="Anwesenheit" state="initialized" sets="copyGplotFile:noArg" attrs="verbose:0,1,2,3,4,5 room group comment:textField-long alias eventMap userReadings:textField-long captionLeft:1,0&quot; endPlotNow endPlotToday fixedoffset fixedrange label nrAxis plotWeekStartDay:0,1,2,3,4,5,6 plotfunction plotsize startDate title DbLogExclude DbLogInclude cmdIcon devStateIcon devStateStyle icon sortby webCmd widgetOverride userattr"> 
			<INT key="CFGFN" value=""/> 
			<INT key="DEF" value="logdb:Anwesenheit:HISTORY"/> 
			<INT key="GPLOTFILE" value="Anwesenheit"/> 
			<INT key="LOGDEVICE" value="logdb"/> 
			<INT key="LOGFILE" value="HISTORY"/> 
			<INT key="NAME" value="Anwesenheit"/> 
			<INT key="NR" value="97"/> 
			<INT key="STATE" value="initialized"/> 
			<INT key="TYPE" value="SVG"/> 
			<ATTR key="DbLogExclude" value=".*"/> 
			<ATTR key="room" value="Plots"/> 
		</SVG>
```
Und passend dazu `configdb filelist`:
```
Files found in database: 
------------------------------------------------------------ 
./configDB.conf 
./FHEM/99_myHelperUtils.pm 
./FHEM/FhemUtils/uniqueID 
./FHEM/template.layout 
./log/eventTypes.txt 
./www/gplot/Anwesenheit.gplot 
./www/gplot/Anwesenheit_PC.gplot 
./www/gplot/az_heizung_plot.gplot 
./www/gplot/bad_heizung_plot.gplot 
./www/gplot/k_heizung_plot.gplot 
./www/gplot/PC_Anwesenheit.gplot 
./www/gplot/sz_heizung_plot.gplot 
./www/gplot/template.gplot 
./www/gplot/templateDB.gplot 
./www/gplot/USV.gplot 
./www/gplot/wz_heizung_links_plot.gplot 
./www/gplot/wz_heizung_rechts_plot.gplot 
```

Bei `configdb fileshow ./www/gplot/Anwesenheit.gplot` wird das richtige Gplot-File ausgegeben, bei `xmllist` steht aber unter `GPLOTFILE` nur der Dateiname und nicht der komplette `configdb` Dateipfad in der Datenbank.

**Comment by klassm** [comment]
Ok, das macht alles Sinn. Mein letztes Problem ist jetzt woran ich festmachen kann dass config-db wirklich verwendet wird. Ich kann ja schlecht nur gucken ob ein / im gplot File vorkommt und dann configdb verwenden. Das macht auch nicht wirklich Sinn.

Gibt es vielleicht ein Gerät mit Typ configdb? Das wäre dann wenigstens zuverlässig.

**Comment by ManOki** [comment]
Vllt hilft das weiter: `<ATTR key="configfile" value="configDB"/>`

```
<Global_LIST> 
		<Global name="global" state="no definition" sets="" attrs="verbose:0,1,2,3,4,5 room group comment:textField-long alias eventMap userReadings:textField-long altitude apiversion archivecmd archivedir archiveCompress autoload_undefined_devices:1,0 autosave:1,0 backup_before_update backupcmd backupdir backupsymlink configfile dnsServer dupTimeout exclude_from_update featurelevel genericDisplayType:switch,outlet,light,blind,speaker,thermostat holiday2we language:EN,DE lastinclude latitude logdir logfile longitude modpath motd mseclog:1,0 nofork:1,0 nrarchive perlSyntaxCheck pidfilename port restartDelay restoreDirs sendStatistics:onUpdate,manually,never showInternalValues:1,0 sslVersion stacktrace:1,0 statefile title uniqueID updateInBackground:1,0 updateNoFileCheck:1,0 version DbLogExclude DbLogInclude cmdIcon devStateIcon devStateStyle icon sortby webCmd widgetOverride DbLogExclude DbLogInclude cmdIcon devStateIcon devStateStyle icon sortby webCmd widgetOverride userattr"> 
			<INT key="DEF" value="no definition"/> 
			<INT key="NAME" value="global"/> 
			<INT key="NR" value="1"/> 
			<INT key="STATE" value="no definition"/> 
			<INT key="TYPE" value="Global"/> 
			<INT key="currentlogfile" value="./log/fhem-2016-08.log"/> 
			<INT key="logfile" value="./log/fhem-%Y-%m.log"/> 
			<ATTR key="DbLogExclude" value=".*"/> 
			<ATTR key="autoload_undefined_devices" value="1"/> 
			<ATTR key="backup_before_update" value="1"/> 
			<ATTR key="configfile" value="configDB"/> 
			<ATTR key="logfile" value="./log/fhem-%Y-%m.log"/> 
			<ATTR key="modpath" value="."/> 
			<ATTR key="room" value="hidden"/> 
			<ATTR key="statefile" value="./log/fhem.save"/> 
			<ATTR key="updateInBackground" value="1"/> 
			<ATTR key="userattr" value="DbLogExclude DbLogInclude cmdIcon devStateIcon devStateStyle icon sortby webCmd widgetOverride"/> 
			<ATTR key="verbose" value="3"/> 
			<ATTR key="version" value="fhem.pl:11756/2016-07-07"/> 
		</Global> 
	</Global_LIST> 
```

**Comment by klassm** [comment]
So ich habe das jetzt mal tatsächlich so eingebaut. Wenn ich 
``<ATTR key="configfile" value="configDB"/>``
einschalte, dann bekomme ich jetzt ein
``08-09 15:25:39.565 8067-8556/li.klass.fhem I/CommandExecutionService: execute() - executing command=configdb fileshow cul_hm_rollladen.gplot, try=0
``
Das müsste eigentlich reichen. Raus geht das dann mit der nächsten Version.

**Comment by ManOki** [comment]
`08-09 15:25:39.565 8067-8556/li.klass.fhem I/CommandExecutionService: execute() - executing command=configdb fileshow cul_hm_rollladen.gplot, try=0`

Ohne korrekten/kompletten Pfad kommt bei mir eine Fehlermeldung. Also `configdb fileshow ./www/gplot/Anwesenheit.gplot` geht, `configdb fileshow Anwesenheit.gplot` kommt `Error on reading Anwesenheit.gplot from database!`

Bin mir allerdings nicht sicher, wie man an den kompletten Pfad rankommt. In der `xmllist` finde ich nichts passendes.

**Comment by klassm** [comment]
Dann wird es eben hart eincodiert ... das müsste sowieso der normale Pfad sein ... :-(

**Comment by ManOki** [comment]
Ok, ich denke auch. Mir ist kein Weg bewusst, den Pfad vom GPlot File zu ändern.

**Comment by ManOki** [comment]
Ok, ich habe es gerade ausprobiert und es funktioniert!! Vielen Dank für die schnelle Umsetzung.

**Comment by klassm** [comment]
Klar gerne ;-)

Am 14.08.2016 16:41 schrieb "ManOki" <notifications@github.com>:
