### ISSUE TITLE
Almost impossible to scroll up on MAX HeatingThermostatPlus Timetable view 

### ISSUE THREAD

**Issue by johol545** [klassm/andFHEM#1042]
When in the timetable view of the MAX HeatingThermostatPlus it's very tricky to scroll up. Most of the time swiping down would instead trigger a page reload, which makes one lose all unsaved 

See screenshot where reload indicator is visible:
![screenshot_20161004-004532](https://cloud.githubusercontent.com/assets/933461/19058002/023b4684-89cc-11e6-8f4b-73198aab4a5a.png)
changes. 

(Android 6.0.1 on a Nexus 5 with andFhem 4.1.9.)

**Comment by klassm** [comment]
Thanks for opening that issue. It will be fixed with the next version of andFHEM (probably next weekend).
