### ISSUE TITLE
Slider werden nicht angezeigt

### ISSUE THREAD

**Issue by sirnoname** [klassm/andFHEM#1073]
Hallo,

ich verwende das neue Bluetooth FHEM Modul für EQ-3 Heizungssteuerung.
In andFHEM wird statt einem slider eine DropDown Auswahl angezeigt mit ein paar Werten.
Auch wird "Slider" aufgelsitet, wenn ich diesen drücke passiert nichts.
Kann ich mehr Infos liefern?

**Comment by klassm** [comment]
Hi,
Klar, eine xmllist vom Gerät wäre super ;-)
Matthias

**Comment by sirnoname** [comment]
Ok, wo wäre die genau?
Auf dem Android Gerät oder in FHEM?

**Comment by klassm** [comment]
Hi,

Einfach in Fhemweb xmllist Name eingeben. Das Ergebnis hätte ich gern .

Matthias

Am 27.12.2016 22:46 schrieb "Martin Wiedenbauer" <notifications@github.com>:

**Comment by sirnoname** [comment]
Ich nehme an dich interessiert nur der Regler Bereich.
In der Web Oberfläche ist dort ein Slider für die Temperatur. Bei FHT80b Raumregler ist es normalerweise ein Dropdown. In andFHEM habe ich statt einem Slider ein Dropdown mit 4.5, slider, 20.0. Drücke ich auf Slider passiert nichts.

         <EQ3BT_LIST>
		<EQ3BT name="heizung.mitte" state="initialized" sets="desiredTemperature:slider,4.5,0.5,29.5,1 updateStatus:noArg boost:on,off mode:manual,automatic eco:noArg comfort:noArg" attrs="alias comment:textField-long eventMap group room suppressReading userReadings:textField-long verbose:0,1,2,3,4,5 cmdIcon devStateIcon devStateStyle icon sortby webCmd widgetOverride userattr"> 
			<INT key="DEF" value="00:1A:22:09:96:2A"/> 
			<INT key="MAC" value="00:1A:22:09:96:2A"/> 
			<INT key="NAME" value="heizung.mitte"/> 
			<INT key="NR" value="30"/> 
			<INT key="STATE" value="initialized"/> 
			<INT key="TYPE" value="EQ3BT"/> 
			<ATTR key="alias" value="Heizung mitte"/> 
			<ATTR key="group" value="Heizung"/> 
			<ATTR key="icon" value="sani_heating_temp"/> 
			<ATTR key="room" value="Wohnraum"/> 
			<STATE key="battery" value="ok" measured="2016-12-28 15:04:21"/> 
			<STATE key="boost" value="1" measured="2016-12-28 15:04:21"/> 
			<STATE key="consumption" value="246.265" measured="2016-12-28 15:04:21"/> 
			<STATE key="consumptionToday" value="13.076" measured="2016-12-28 15:04:21"/> 
			<STATE key="consumptionYesterday" value="173.281" measured="2016-12-28 14:55:50"/> 
			<STATE key="desiredTemperature" value="22" measured="2016-12-28 15:04:21"/> 
			<STATE key="ecoMode" value="0" measured="2016-12-28 15:04:21"/> 
			<STATE key="errorCount-setDesiredTemperature" value="28" measured="2016-12-27 01:15:39"/> 
			<STATE key="errorCount-updateStatus" value="1390" measured="2016-12-27 01:15:18"/> 
			<STATE key="errorCount-updateSystemInformation" value="25" measured="2016-12-27 01:03:18"/> 
			<STATE key="firmware" value="110" measured="2016-12-28 14:55:21"/> 
			<STATE key="mode" value="Automatic" measured="2016-12-28 15:04:21"/> 
			<STATE key="valvePosition" value="80" measured="2016-12-28 15:04:21"/> 
			<STATE key="windowOpen" value="0" measured="2016-12-28 15:04:21"/> 
		</EQ3BT> 
	</EQ3BT_LIST>

**Comment by klassm** [comment]
Interessant. Man darf wohl am Ende der slider setList eine 1 anhängen. 

> if the modifier is of the form ":slider,<min>,<step>,<max>[,1]", then a javascript driven slider is displayed. > The optional ,1 at the end avoids the rounding of floating-point numbers.

Ich akzeptiere den Wert jetzt einfach auch. Damit dürfte das Thema für dich erledigt sein.

**Comment by sirnoname** [comment]
Besten Danke, derzeit sehe ich über den Playstore allerdings kein Update und die installierte Version sagt 26.12.2016.

**Comment by klassm** [comment]
Jap ich habe auch noch keine Version hochgeladen - mache ich vermutlich am Wochenende.
