### ISSUE TITLE
EQ3 Bluetooth Slider Probleme

### ISSUE THREAD

**Issue by sirnoname** [klassm/andFHEM#1076]
Hallo,

mein erstes Slider Problem mit den EQ-3 Bluetooth Reglern wurde behoben. Vielen Dank mal soweit. Leider lässt sich der jetzt angezeigt Slider so nicht nutzen. Wenn ich z.B. bei 5°C bin und den Regler auf 20 °C ziehe, dann bleibt er für ca. 1 Sekunde auf 20°C, lädt dann anscheinend neu und setzt sich wieder auf 5°C weil die Regler einige Zeit brauchen. Wenn ich manuell aktualisiere geht der Regler auf 20°C.
Mich wundert zudem das die Slider nicht in die Favoriten gezogen werden wenn man den Regler als Favorit hinzufügt .Man kann sie unter Favoriten nicht wie die Buttons sofort bedienen kann. Mann muss also erst den Regler auswählen, nach unten scrollen ... Ist das so gewollt oder ein Bug?

Kleine Bemerkung noch zur Aktualisierung nach dem Starten der App. Der Erklärungs Text dort ist negiert. Ich würde mich zudem freuen wenn das Aktualisieren im Hintergrund stattfinden würde, nachdem/während die App gestartet ist.

Ein frohes neues Jahr!

**Comment by klassm** [comment]
Hi,

nach jedem Schaltvorgang holt sich andFHEM den aktuellen Gerätezustand von FHEM. Je nachdem wie der Zustand dann gesetzt ist kann das gerade richtig oder eben verzögert falsch sein. Um ehrlich zu sein: Ich habe keine Ahnung wann die EQ-3 Regler den Zustand in FHEM richtig setzen. Das spiegelt das Verhalten von andFHEM wieder. Wenn du mir sagst, dass nach 5 Sekunden der Zustand meistens richtig ist kann ich die Aktualisierung auch so einstellen. AndFHEM kann nur eben nicht _wissen_ wann die Aktualisierung stattgefunden hat, weil es so etwas wie Push-Nachrichten für FHEM nur als Add-On (z.B. GCM) gibt.

Favoriten gibt es in andFHEM nur auf Geräteebene, nicht als Funktion. Du kannst höchstens das Gerät als webcmd-Gerät (siehe Hooks) einrichten und dann deinen Regler als Webcmd im Gerät definieren. Dann hättest du den Knopf in der Übersicht. Ob das dann aber das richtige Verhalten ist ...
Generell irgendwelche Regler für die Heizung als Favorit zu definieren halte ich für gefährlich. Die Frage ist ja immer was der Haupt-Usecase ist. Ist das das Ablesen der gerade aktuellen Temperatur? Oder die Einstellung der Temperatur? Beides gleichzeitig anzuzeigen wird schlicht zu viel. Wenn man das bei jedem Gerät macht wirkt die App sofort komplett überladen.

Es gibt in den Einstellungen eine Option, mit der man nach dem Applikationsstart die Geräteliste aktualisieren kann. Beim reinen Applikationsstart findet keine Aktualisierung statt. Dann wird nur vom Dateisystem der letzte Zustand gelesen - das kann schonmal 2-3 Sekunden dauern.

Was meinst du genau damit, dass der Erklärungstext negiert ist?

Viele Grüße,
Matthias

**Comment by sirnoname** [comment]
Hi,

wenn ich mir das fhem WEB Interface anschaue, dann setze ich einen Slider Wert auf z.B. 20°C und es wird nach ca. 4-5 Sekunden erst noch einmal nachgefragt. Getestet mit Setzen von 5 auf 20 dann gleich wieder auf 10°C und den EQ-3 Bluetooth. Der letzte Schritt wird nach 4 Sekunden auf 20 zurückgesetzt und 10 ignoriert. Entwickler von Plugins werden wohl nach dieser Oberfläche arbeiten, wo auch immer die 4 Sekunden herkommen. Ich habe leider kein anderes Gerät mit Slider.
Der Haupt Use Case ist bei mir das schnellste Einstellen der Temperatur.

Der Erklärungstext zum Aktualisieren der Geräteliste nach dem Programmstart ist richtig, nur ändert er sich beim Entfernen des Hacken in "nicht". Dadurch meint man diese Option anhacken zu müssen. Interaktive Erklärungstexte. Ich bin da als neuer Benutzer drübergestolpert.

Warum braucht es 3 Sekunden beim Start? Hat die FHEM API ein Delay?
Versteh mich nicht falsch, 2 Sekunden sind nicht die Welt. Die Programme von manchen Smarthomes sind mit Minuten unterwegs. Mit Chrome 2 Sekunden mit andFHEM 3 Sekunden bis man Schalten kann. Man könnte also Punkten indem man z.B. die Button gleich anzeigt. Ausgegraut. Dann orientiert sich der Benutzer schon mit seinen Fingern bis die Button aktiv sind. Das gäbe ein flüssigeres Bedienungsgefühl.

Vielen Dank für deine Mühe!

**Comment by klassm** [comment]
Hi,

ok für den ersten Punkt bräuchte ich von dir nur eine xmllist für das Gerät. Dann verzögere ich die Aktualisierung auf 6 Sekunden - dann sollte der Zustand ja sicher übernommen sein.

Ja, diese interaktiven Texte - Google will die mittlerweile so haben. Hast du denn einen Vorschlag wie man das besser schreiben kann?

Nein, das Delay hat mit FHEM recht wenig am Hut. Wenn die Applikation gestartet wird und nicht im Cache liegt - das kommt zumindest bei mir Recht selten vor - müssen einige Dinge initialisiert werden:
* Laden des lokalen Caches (d.h. Einlesen einer andFHEM Variante der xmllist) - das dauert am Längsten, IO ist teuer. Unter Umständen wird auch die Geräteliste vom Server geholt. Das passiert aber nur wenn lokal keine Daten gespeichert sind. Diesen Punkt kann man nicht wirklich auslagern. Bis hierhin ist die App nicht bedienbar.
* Verbindung mit Google Billing - das braucht man für die Inapp-Purchases. Das ist meistens recht schnell. Wobei "recht" relativ ist - ich habe noch nie einen Profiler drauf angesetzt.
* Laden der Favoriten. Das ist egal.

Im Prinzip müsste ich wirklich mal einen Profiler drauf hetzen und mal gucken wo die Zeit hängen bleibt.

Matthias
