### ISSUE TITLE
widgets problem

### ISSUE THREAD

**Issue by curzon01** [klassm/andFHEM#1091]
Since 4.3.9 widgets has problems:

- Previously created widgets content (e.g 2x1 with temp/hum) are not updated - updated only on schedule (Aktualisierungsinterval). Tried: Tab on widget, update, new values displayed on detailed screen - go back to home screen with widget display still old values.

- newly created widgets do not show any content anymore and they are not tabable.

**Comment by curzon01** [comment]
reboot the device ones still kept the problem.
reboot the device a second time solve the problem - no issue, sorry

**Comment by klassm** [comment]
Strange. If it happens again please feel free to open the issue again.

**Comment by curzon01** [comment]
Happens again, widgets are not updated sometimes, e.g. switch widget: tabbing the widget will do the action but widget stay on old state. In this situation also refresh complete list within andFhem do nothing, no update of any widget.
Killing the app, restart it and refresh within app helps. Also refresh widget does not work at all,even not after aüp restart (never works).

**Comment by klassm** [comment]
Hm I still cannot reproduce the problem, if though I believe there is a problem ...

When the bug occurs and you refresh the device list within andFHEM - does nothing get updated then or are only the widgets stuck? 
When you have executed that action, can you attach a log file (within the settings you can send a log file) to this issue? Maybe we see more then.
What launcher are you using. I know of some bugs (even though it was Samsung then) having issues with widgets.

Matthias

**Comment by curzon01** [comment]
When the bug occurs and I refresh device list within andFHEM, it will update all within andFHEM but without the widgets on screen.

Attached find a log where I tried: 
- switch action within andFHEM and refresh within andFHEM
- place a new 1x1 widget on screen (but this new wdget show only the andFHEM default icon).
[andFHEM-1248964968.log.zip](https://github.com/klassm/andFHEM/files/801862/andFHEM-1248964968.log.zip)

I'm using the default launcher EMUI 4.1.1 from my current Huawei P9 Lite.

**Comment by klassm** [comment]
@curzon01 Well I tried to follow your steps - however, I still cannot reproduce the problem. The small widgets is shown correctly.
Just to find out whether there's a problem with the launcher - can you try to install some other launcher, like Google Now Launcher or so, and see whether you can reproduce the error there?

Oh by the way - you have GCM enabled. Widgets are not automatically updated on GCM notifications. This only happens when the respective checkbox within the settings is enabled.

**Comment by curzon01** [comment]
I will try to have a look reproducing the issue with another launcher.

BTW: I think GCM update notification is enabled when the checkbox has a check mark: 
![screenshot_2017-02-27-11-32-06](https://cloud.githubusercontent.com/assets/6636844/23358094/e18c1b92-fce0-11e6-995b-a6eacc8933fd.png)

**Comment by klassm** [comment]
One problem found: widgets where updates twice instead of only once when sending commands. No idea whether this could have any effects - it should make updates faster even though.

**Comment by curzon01** [comment]
Since 4.4.4 I didn't saw issue again on my device. It seems it ist solved, great work. Would WE close this issue and reopen it again when it happens again or should I observe this one week again?

**Comment by klassm** [comment]
Hi,
as I still don't know the reason I suppose it's fair to leave it open for the next week.
Matthias
