### ISSUE TITLE
Hide specific groups?

### ISSUE THREAD

**Issue by stratmaster** [klassm/andFHEM#1096]
Is it possible to hide specific groups - including its devices - within andFHEM?

**Comment by klassm** [comment]
Well within the preferences there's an option called function order, which allows you to reorder and hide groups. However, this only applies to groups andFHEM knows about. If you want to hide groups generically, add another FHEMWEB device within your FHEM instance and define a "hiddengroup" attribute.

**Comment by stratmaster** [comment]
Thank you, I'll give it a try!
