### ISSUE TITLE
Cannot select client certificate

### ISSUE THREAD

**Issue by zilon84** [klassm/andFHEM#1107]
Hello,

I am using andFHEM on my Oneplus 2 running LineageOS 14.1 and try to select the client cert stroed on my device but andFHEM does not show an certificates or other data stored in the folder that is selected by default. Futher I can only step up the path and I am not able to select any folder.

**Comment by klassm** [comment]
Well I don't know what lineageOS does when picking files. Vanilla Android works somehow ...

I've tried to migrate the file picker dialog to some utitlity library. Let's see whether this works better for you. No guarantees even though.

**Comment by zilon84** [comment]
Thx. It's working now.

**Comment by klassm** [comment]
Perfect thanks for the feedback
