### ISSUE TITLE
Preferences - Auto Update

### ISSUE THREAD

**Issue by curzon01** [klassm/andFHEM#1111]
"Preferences/Auto Update" (Einstellungen/Automatisches Update) 

last choice 
* "every 48 hours" (alle 48 Stunden) 
not selectable

on mobile: Selection are simply not taken
on tablet: App freeze, not usable anymore

andFHEM Release 4.5.1

**Comment by klassm** [comment]
Thanks for reporting. Fix will be contained in the next release.
