### ISSUE TITLE
User root CA in Android not used for verification?

### ISSUE THREAD

**Issue by ypid** [klassm/andFHEM#1112]
Hi

I imported my own internal root CA into the Android trusted certificates store. The root ca signs a intermediate ca which in turn issued a server cert for the host I run fhem on. When I visit this host from Chromium I get no certificate error.

However, when I open the URL with fhem, I get "Accept Unknown certificate".

A few things to note:

* I have set `Name constraints` on the root and intermediate (https://developer.mozilla.org/en-US/docs/Mozilla/Security/x509_Certificates)
* The intermediate was not imported in Android but is sent by the webserver as usual. For testing, I imported the intermediate in Android to check if the app can not handle cert chaining but that seems not to be the issue.

Android 7.1.2; andFHEM 4.5.1.

**Comment by klassm** [comment]
Well, as far as I can see apps simply use certificates from Android's root certificate store. There's no such thing as app specific certificate handling (https://developer.android.com/training/articles/security-ssl.html). The intermediate certiciate seems to be required on the device (at least if I understood the docs right).

The only thing I can offer is to have a look at the logs (if you attach them). Maybe there's some info in there on what went wrong.

**Comment by ypid** [comment]
Thanks for looking into this. I checked the logs but there are no issues logged. When I clear the trusted certificates in andFHEM and reconnect, I get the following:

```
04-22 14:02:29.764 21832 21916 I CommandExecutionService: executeSafely(command=Command{command='set light on', connectionId=Optional.absent()}, delay=0)
04-22 14:02:29.790 21832 21916 D NetworkSecurityConfig: No Network Security Config specified, using platform default
04-22 14:02:29.791 21832 21916 I FHEMWEBConnection: executeTask command set light on
04-22 14:02:30.403  3773 21921 D NuPlayerDriver: notifyListener_l(0xf0008900), (1, 0, 0), loop setting(0, 0)                                                                                                       
04-22 14:02:30.403  6409 21919 D MediaPlayer: setSubtitleAnchor in MediaPlayer
04-22 14:02:30.407  4704  6955 I MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10024/6409 clientId=android.media.AudioManager@cbd270f req=3 flags=0x0
```

The sound entries are related to the notification sound that comes with the "Accept Unknown certificate" notification.

I tried around and read the https://developer.android.com/training/articles/security-ssl.html without finding the issue. I also debugged this with with `openssl s_client` and checked that the connection has the servername as TLS SNI set. Also made SNI optional by making this cert/vhost/backend the default. And I disabled required client certs which I also enabled. The "Accept Unknown certificate" error still appears.

After this, I pasted the URL in another app to see how they handle it. I already saw Chromium use the user CA. F-Droid does not use it and logs the expected "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.". Looking further, seems that the way user CAs are handled has been [changed in Android Nougat ](https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html). Seems that Android does not provide means for apps to make this configurable (ref: https://stackoverflow.com/questions/40363553/list-certificate-stored-in-user-credentials) except by changing the manifest.

Not sure why Chromium uses the user CAs and how that could be added to andFHEM. But it is a system app and CopperheadOS might have enabled this.

Do you see any way to make this configurable without changing Androids default not to trust user CAs by default (which I think is a reasonable default)?

**Comment by klassm** [comment]
Thanks for adding those links. I did not yet know about those changes in
Android Nougat. Well, I suppose the most sensible default for andFHEM is to
just trust all user certificates by default. This should fix your issue.

Am 22.04.2017 14:54 schrieb "Robin Schneider" <notifications@github.com>:

**Comment by ypid** [comment]
I guess this is the only way then. Would be interesting to see how other apps handle this. Users who care enough to run their own root CA can use `name constraints` to mitigate compromise of the self run root CA so your fix would work for me.

**Comment by klassm** [comment]
Well, I don't think that the top 99 percent of applications got that kind of problem, as they only access one backend server (which is some arbitrary trusted url). The only application I can imagine having the same kind of problem is a browser, because a browser also allows a user to access any url entered.

**Comment by ypid** [comment]
True, that is what I meant with other apps :wink: Thanks.

**Comment by ypid** [comment]
Confirmed working after with 4.5.3. Now my certificate stuff is configured in one place only (root ca in Android trusted certificates). Thanks again :+1:
