### ISSUE TITLE
Connections Dialog is not working

### ISSUE THREAD

**Issue by ManOki** [klassm/andFHEM#1128]
Hi,

i updated to the newest andFHEM version from google playstore and now, i cannot open the connections dialog/window anymore. I tested 3 devices (phone and 2 tablets, android 7.1.2 and 5.1.1).

I guess, this issue is caused by the new design.

Greets, ManOki

**Comment by ManOki** [comment]
Workaround: Export settings from already established app setup and import in newly installed. Does not work for completly new installations.

**Comment by klassm** [comment]
The one thing I did not test ... sorry for that ...

**Comment by ManOki** [comment]
Never mind, thanks for this great project and the quick response!

**Comment by klassm** [comment]
Sure. By the way: the fix is released and should arrive on your device shortly.
