### ISSUE TITLE
No switches for most devices

### ISSUE THREAD

**Issue by elhennig** [klassm/andFHEM#1133]
I am using Android 7.1
Since the last update there are no switch buttons anymore for dummy devices I use to toggle wifi for example. IT switch devices still work well. Also widgets are not updated anymore.

**Comment by klassm** [comment]
Hi @elhennig 

Thanks for reporting this issue. Currently, I am trying to reproduce your issues. I just started with the toggle buttons for dummy devices. What does the setList of your devices look like?
Using "on off" as setList, toggle buttons appear. Using "on,off", no buttons appear. However, this does not seem to be a valid specification.
Maybe you can just add an example of your setList configuration.

Matthias

**Comment by klassm** [comment]
Concering widget updates I have found an issue where an "invalid" setList (without on off values) can crash the update service. I suppose this happened on your device. #1134

**Comment by elhennig** [comment]
I do not have setList in my dummys, I am just using webCmd
For example:
attr WLAN_PI webCmd on:off
and then define notify with the appropriate command.

**Comment by klassm** [comment]
Hi @elhennig 

thanks for that hint - didn't think of switching over webcmd commands here. Still, I've added that option again.

Matthias

**Comment by elhennig** [comment]
I added setList attributes to the dummys and this helps as a workaround. Thanks a lot!
