### ISSUE TITLE
Widgets do not refresh with update inside App

### ISSUE THREAD

**Issue by ManOki** [klassm/andFHEM#1137]
Hi,

i'm using the latest version from the playstore. Lately i noticed, that widgets do not update their status (e.g. on/off), while i update inside the app. So inside, i see the current correct status of a device (after a refresh), but when i go to the homescreen, there is still the old status in the widget.

I am on Android 7 with Trebuchet Launcher and no gcmsend.

EDIT: Maybe corelated with #1091 

Greets, ManOki

**Comment by ManOki** [comment]
I also recognized, that all widget status get refreshed, if only one is clicked. I don't know, if this is truly causal or just a timeout to refresh the widget anyway.

**Comment by klassm** [comment]
Hi,

thanks for your bug report. I just tried to reproduce your issue - however, when changing the state within FHEM and refreshing a device list within the app, the widget is correctly updated for me. What version of andFHEM do you run? For the previous version, the update service could be possibly broken (whenever some specific scenario occurred, preventing widgets from updating).

Usually, all widgets are updated. There is some mechanism to update just a specific widget - however, this one is used very rarely within the app.

Matthias

**Comment by ManOki** [comment]
Hi,

i'm using version 4.6.1.

Is it possible to debug this behaviour somehow. So that i can see, there is an update/repaint command for the widget, which is maybe not directly executed?

Another case i recognized: ie. light is switched on outside andFhem. After updating inside the app (light on), the widget still shows light off. But if i click it, the light goes off. imo the widget should still send "light on".

Does the widget hold itself the status and send the command based on this status -or- does the widget uses the status inside the app and send commands based on that?

Greets, ManOki

**Comment by klassm** [comment]
Hi @ManOki 

well, somehow the last update from 4.6.1 to 4.6.2 was not published. Without this fix, the widget update service may crash preventing widgets from updating. This could be an explanation for your behaviour. I'll look into this to find out what happend to the update ...

Matthias

**Comment by ManOki** [comment]
Hi,

i got the update and tested it yesterday. It is updating, sometimes with a delay of 10-20 seconds, but thats ok for me.

I'll close the issue.

Greets, ManOki
