### ISSUE TITLE
Deleting hooks attribute does not revert default behaviour

### ISSUE THREAD

**Issue by ManOki** [klassm/andFHEM#1144]
Hello,

i used hooks from [Hooks](http://andfhem.klass.li/hooks/) and added `OnButton` to a dummy. After i deleted the attribute inside fhem, the button inside andFhem did not switch back to the default behaviour, ie. one on and one off button.

Greets, ManOki

**Comment by klassm** [comment]
Should be resolved already?

**Comment by ManOki** [comment]
Jep, is solved. I got confused, because a dummy with just on/off has only a single toggle button, but every lamp has two buttons as default.
