### ISSUE TITLE
WebCmd in Widgets

### ISSUE THREAD

**Issue by ManOki** [klassm/andFHEM#1173]
Hi,

i got an vacuum cleaner, which i want to control via web cmd. there are basically 2 commands to start and stop cleaning, "start" and "charge".

```
Internals: 
   CFGFN 
   CHANGED 
   DEF        Staubsaugroboter 6a67684252755168564749707a614d78 
   FD         21 
   NAME       vacuum 
   NR         165 
   STATE      disconnected 
   TYPE       XiaomiDevice 
   device_type 
   mac        LOCALNETWORK 
   model      rockrobo.vacuum 

Attributes: 
   subType    VacuumCleaner 
   webCmd     start:charge 
   webcmdDevice true 
   widget_name Saugroboter 
```

I defined both commands as `webCmd` and added the `webcmdDevice` attribute to inform andFhem to display those webCmd. Inside the app, this looks like this:

![webcmd](https://img1.picload.org/image/dglirrpl/webcmd.png)

Now i want to add a widget, which offers the same functionality. Unfortunately there is no such widget, you are only able to add a default "on/off" widget, looking like this:

![onoff](https://img1.picload.org/image/dglirrpa/anaus.png)

The other opportunity are two widgets, one for each command:

![state](https://img1.picload.org/image/dglirrpi/zielzustand.png)

Is it possible to add a new widget for `webCmd` or update the default "on/off" using `webCmd`?

Greets
ManOki

**Comment by klassm** [comment]
Well, I suppose it would not really be helpful to add another widget supporting two webcmd commands. What you can do is add on/off commands and provide them with an eventMap, telling on to be start and off to be charge. With a little notify, you could put those back to the real commands. That's at least an idea :-)

**Comment by ManOki** [comment]
Ok, good idea, i have done that with
```
attr vacuum eventMap start:on charge:off
attr vacuum stateFormat {ReadingsVal("vacuum","in_cleaning","") eq "yes"?"on":"off"}
```

Now i can add a 2x1 widget. The 1x1 widget has the same problem as mentioned in #1174.
