### ISSUE TITLE
Add controls.txt to update gcmsend.pm

### ISSUE THREAD

**Issue by ManOki** [klassm/andFHEM#1175]
Hi,

please provide a controls.txt to support the fhem `update` command as described [here](https://wiki.fhem.de/wiki/Update).

This allows users to automatically install and update your 98_gcmsend.pm file in a more constructive manner.

Just use this github directly, i.e. the raw url: `https://raw.githubusercontent.com/klassm/andFHEM/master/fhem_modules/98_gcmsend.pm`

Greets
ManOki

**Comment by klassm** [comment]
Well, I have added a controls_gcmsend.txt:
https://github.com/klassm/andFHEM/blob/master/fhem_modules/controls_gcmsend.txt

However, this is a little silly, as FHEM requires a different file size as they describe in the docs ... well, it works for now....

**Comment by klassm** [comment]
@ManOki Can you check whether this works for you? If it does, I'd document the behavior and close the issue.

**Comment by cyberman54** [comment]
I updated the 98_gcmsend.pm manually a few days ago

Now 

>update add https://github.com/klassm/andFHEM/blob/master/fhem_modules/controls_gcmsend.txt
>update all

results in

2017.10.08 22:48:08 1 : gcmsend
2017.10.08 22:48:10 1 : nothing to do...

=> it seems to work

**Comment by klassm** [comment]
Thanks for the feedback!

**Comment by ManOki** [comment]
Sorry for late response. @cyberman54 you add the wrong url, you have do add the raw file, not the github-webpage (fhem update is not able to interpret html):

`update add https://raw.githubusercontent.com/klassm/andFHEM/master/fhem_modules/controls_gcmsend.txt`

And the file content is wrong. I did an update and fhem created an absolute path, like in the controls.txt:

`/opt/fhem/https:/raw.githubusercontent.com/klassm/andFHEM/master/fhem_modules/98_gcmsend.pm`

The path inside the controls.txt has to be relative to the fhem working directory and the http path, i.e.

```
DEL FHEM/98_gcmsend.pm
UPD 2017_09_24_10:49:21 12314 FHEM/98_gcmsend.pm
```

Thererfore, if the controls_gcmsend.txt url is `https://raw.githubusercontent.com/klassm/andFHEM/master/fhem_modules/controls_gcmsend.txt`, the 98_gcmsend.pm file has to be downloadable at  `https://raw.githubusercontent.com/klassm/andFHEM/master/fhem_modules/FHEM/98_gcmsend.pm`.
You missed the date `2017_09_24_` as well.

Greets, ManOki

**Comment by klassm** [comment]
Hi @ManOki 
thanks, I tried to adapt the controls file. Can you try it again?

Well I have no idea how to specify a CHANGED file. Any ideas?

Matthias

**Comment by ManOki** [comment]
The update process executed successfully this time. You can upload a CHANGED file at `https://raw.githubusercontent.com/klassm/andFHEM/master/fhem_modules/CHANGED`.

Just see another CHANGED file like [this](https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r32/CHANGED). You have to insert a date and some bullet points (i guess).

**Comment by klassm** [comment]
There you go.

**Comment by ManOki** [comment]
Ok, seems to be fine. I already did an update and i don't know how to revert.

**Comment by cyberman54** [comment]
There is still wrong path given in the description at http://andfhem.klass.li/installation/

update add https://github.com/klassm/andFHEM/blob/master/fhem_modules/controls_gcmsend.txt

It should be:

update add https://raw.githubusercontent.com/klassm/andFHEM/master/fhem_modules/controls_gcmsend.txt

**Comment by klassm** [comment]
Yip, you're right. I've updated the docs. Thanks!
