### ISSUE TITLE
Android 8 "battery optimization" breaks widgets

### ISSUE THREAD

**Issue by larskoenig** [klassm/andFHEM#1180]
In Android 8 (Oreo), a new per-app "battery optimization" feature was introduced. Rarely used apps are automatically set to "Optimizing battery use" mode. 

If this is performed for andFHEM, it breaks (at least) the 1x1 toggle widget. Widgets do not respond unless the app is still open in the app drawer, which makes me suspect that the "battery optimization" option kills/freezes all andFHEM processes upon closing.

This can be circumvented by manually setting "Not optimized" for andFHEM.

Using andFHEM 4.7.3 on Nexus 5X with Android 8.0.0 (OPR4.170623.009); this is not fixed by #1174

**Comment by larskoenig** [comment]
Seems that this is "App standby" (https://developer.android.com/training/monitoring-device-state/doze-standby.html) and has been around since Android 6. However, it always worked fine before the recent update to Oreo, although I never actually open the andFHEM app.

**Comment by klassm** [comment]
Well, if I understood this correctly the only thing I can do is fire an
intent which lets you add the app to the whitelist ... As far as I can see
there is no general "fix".

Am 10.10.2017 11:49 schrieb "larskoenig" <notifications@github.com>:

**Comment by larskoenig** [comment]
I find it strange that it happened just now and not already with Marshmallow, not sure what they changed in that regard. 

Anyway, once Oreo becomes more widespread you will probably see other reports like this, if this is really a new issue. So at least you have a clue now what can be done to work around that :)

**Comment by klassm** [comment]
With the current beta version this behaviour is probably resolved.
