### ISSUE TITLE
Evaluate FHEMWEB column attribute

### ISSUE THREAD

**Issue by klassm** [klassm/andFHEM#1182]
```
column
Allows to display more than one column per room overview, by specifying the groups for the columns. Example:
attr WEB column LivingRoom:FS20,notify|FHZ,notify DiningRoom:FS20|FHZ
In this example in the LivingRoom the FS20 and the notify group is in the first column, the FHZ and the notify in the second.
Notes: some elements like SVG plots and readingsGroup can only be part of a column if they are part of a group. This attribute can be used to sort the groups in a room, just specify the groups in one column. Space in the room and group name has to be written as %20 for this attribute. Both the room name and the groups are regular expressions.
```

**Comment by klassm** [comment]
Hallo Matthias.

und wenn man es nur mal "basic" implementiert, sprich werden angegebene colums in der config gefunden dann werden zuerst diese verwendet/gezeigt und dann der Rest Alphabetisch wie bisher.
Dann würde es sich gleich verhalten wie in FHEM (soweit ich es getestet habe).
So habe ich z.B.: meine Räume definiert:

attr WEB column Julian:Szenen,Lampen,Geräte Küche:Szenen,Lampen,Geräte Schlafzimmer:Szenen,Lampen,Geräte 

Wäre toll wenn du da was machen könntest.
Natürlich wäre auch die manuelle Sortierung eine Möglichkeit.
Glaube aber dass das Auswerten des obigen attr die schönere Möglichkeit wäre :-)

Danke

**Comment by popy2k14** [comment]
Danke Matthias fürs erstellen des Tickets.
lg Tobias
