### ISSUE TITLE
High Battery Usage on "Remote Widget Refresh"

### ISSUE THREAD

**Issue by ManOki** [klassm/andFHEM#1183]
Hi,

i recently noticed that my phone (LineageOS 14.1 with Android 7.1.2) battery runs down very fast. I used BetterBatteryStats to observe which app causes such a high battery drain and identified andFHEM which holds the CPU constantly in a high power mode.

<img src="https://user-images.githubusercontent.com/1769457/31881692-97fd41ee-b7e4-11e7-9e99-cb1496c6453b.png" width="400">

<img src="https://user-images.githubusercontent.com/1769457/31881698-9dc754ca-b7e4-11e7-985a-a4a879aca5a3.png" width="400">

I have 10 1x1 Widgets and "Remote Widget Refresh" enabled. If i uncheck this single option, everything is back to normal.

Funny thing is, that i have the almost same setup on my tablet (LineageOS 14.1 with Android 7.1.2) with even more widgets but not such high Kernel Wakeups due to andFHEM.

I don't know, if this issue is related to #1180 because i use Android 7 and "Doze"/Battery Optimization is enabled for andFHEM.

Greets, ManOki

**Comment by klassm** [comment]
Hi,

Just in case - do you have GCM /FCM enabled and how often do you push
messages / updates to your phone?

The last time I looked a battery issue up (some days ago) just too many
messages were pushed to the phone, keeping the phone awake all the time.

Matthias

Am 23.10.2017 12:24 schrieb "ManOki" <notifications@github.com>:

**Comment by ManOki** [comment]
Hi,

GCM/FCM is not enabled, WiFi Refresh is set to every 10 minutes and mobile refresh every 30 minutes. There is no difference whether i'm inside my own WiFi, another one or just mobile (HSPA+).

Greets, ManOki

**Comment by JorinL** [comment]
Do you have "Widgetupdates  get data from server" enabled? For me it was holding andFHEM long time awake like in your battery stats. 
You can give it a try (I'm currently trying to talk over this switch).

**Comment by ManOki** [comment]
I'm not using Google+ and i don't know, if @klassm does. Just share your thoughts here on github, please.

**Comment by JorinL** [comment]
He does - its his group :-)
I'm not  any farther now with any thought.
I only watched my battery drain with that switch enabled.

**Comment by ManOki** [comment]
Ok, thanks for the hint @JorinL

**Comment by JorinL** [comment]
Please try the following - add andFHEM in Settings > Battery > Not watched Apps .
Eventually even you instance gets killed sometimes by Android and every time it recreates it will stay awake long time and makes initializing stuff.

For me it fixed a problem with updating widget states. And at least with the Switch (Widgetupdates get data from server) disabled I ran the app with 28 mAh on 14 hours.

**Comment by ManOki** [comment]
I tested disabling doze (battery optimization) for andFHEM, but didn't recognize any improvement for my situation. If i just disable the switch, i get almost the same battery usage.

As i wrote, disabling the switch is just a workaround to prevent the battery drain, this is not the final solution where the whole functionality should remain.

**Comment by JorinL** [comment]
Yep its only a workaround - the question is what functions are behind that switch :-)
Which data is when collected from the server and on which timing oder trigger.

**Comment by klassm** [comment]
Well - if the switch is enabled, every widget update triggers a `xmllist $deviceName` and shows the newly fetched data. If having ten or more widgets Android will wake up every minute (in a worst case scenario).

You can see that behaviour when looking at the application log (you can hit 'Send application log') within the preferences, send it to yourself and unpack the zip). You'll see each server call in the log.
Probably this is the cause for the high battery usage, as Android cannot go to deepsleep then.

For now I changed the behaviour from RTC_WAKEUP (wakeup whenever the update is scheduled) to RTC (do the update when the devices does wake up the next time). This should improve the battery behaviour.

**Comment by klassm** [comment]
By default I'd release that fix with the next release.
