### ISSUE TITLE
GCMSend error while loading with Perl 5.24

### ISSUE THREAD

**Issue by ManOki** [klassm/andFHEM#1184]
Hi,

i installed the gcmsend module according to your [webpage](http://andfhem.klass.li/installation/) via `update add https://github.com/klassm/andFHEM/blob/master/fhem_modules/controls_gcmsend.txt`.

If i try to define gcmsend `define gcm gcmsend` an error occurs: `Cannot load module gcmsend`

Inside the log i see the following.
```
2017.10.23 16:15:43 1: PERL WARNING: Scalar value @a[1] better written as $a[1] at ./FHEM/98_gcmsend.pm line 35.
2017.10.23 16:15:43 1: PERL WARNING: Scalar value @a[...] better written as $a[...] at ./FHEM/98_gcmsend.pm line 45.
2017.10.23 16:15:43 1: PERL WARNING: Scalar value @array[...] better written as $array[...] at ./FHEM/98_gcmsend.pm line 79.
2017.10.23 16:15:43 1: reload: Error:Modul 98_gcmsend deactivated:
 Can't use a hash as a reference at ./FHEM/98_gcmsend.pm line 195.
```

My current perl version is 5.24.1 (debian stretch).

Greets, ManOki

**Comment by JorinL** [comment]
I don't know if there is already another new version of the 98_gcmsend.pm but on my Pi its running pretty fine. Yes the Perl Warnings are coming  - but it is working.

`2017.10.11 22:24:52 1: PERL WARNING: Subroutine roomsAdd redefined at ./FHEM/99_myUtils.pm line 9, <$fh> line 6.
2017.10.11 22:24:53 1: PERL WARNING: Subroutine roomsRemove redefined at ./FHEM/99_myUtils.pm line 29, <$fh> line 6.
2017.10.11 22:25:26 1: PERL WARNING: Scalar value @a[1] better written as $a[1] at ./FHEM/98_gcmsend.pm line 35, <$fh> line 184.
2017.10.11 22:25:26 1: PERL WARNING: Scalar value @a[...] better written as $a[...] at ./FHEM/98_gcmsend.pm line 45, <$fh> line 184.
2017.10.11 22:25:26 1: PERL WARNING: Scalar value @array[...] better written as $array[...] at ./FHEM/98_gcmsend.pm line 79, <$fh> line 184.
2017.10.11 22:25:26 1: PERL WARNING: Using a hash as a reference is deprecated at ./FHEM/98_gcmsend.pm line 195, <$fh> line 184.
2017.10.11 22:25:26 1: PERL WARNING: Using a hash as a reference is deprecated at ./FHEM/98_gcmsend.pm line 199, <$fh> line 184.
2017.10.11 22:25:26 1: PERL WARNING: Using a hash as a reference is deprecated at ./FHEM/98_gcmsend.pm line 201, <$fh> line 184.
2017.10.11 22:25:26 1: PERL WARNING: Scalar value @parts[0] better written as $parts[0] at ./FHEM/98_gcmsend.pm line 220, <$fh> line 184.
2017.10.11 22:25:26 1: PERL WARNING: Scalar value @parts[1] better written as $parts[1] at ./FHEM/98_gcmsend.pm line 221, <$fh> line 184.
2017.10.11 22:25:26 1: PERL WARNING: Scalar value @parts[2] better written as $parts[2] at ./FHEM/98_gcmsend.pm line 222, <$fh> line 184.
2017.10.11 22:25:26 1: PERL WARNING: Scalar value @parts[3] better written as $parts[3] at ./FHEM/98_gcmsend.pm line 225, <$fh> line 184.
2017.10.11 22:25:26 1: PERL WARNING: Scalar value @parts[3] better written as $parts[3] at ./FHEM/98_gcmsend.pm line 226, <$fh> line 184.
2017.10.11 22:25:26 1: PERL WARNING: Scalar value @parts[3] better written as $parts[3] at ./FHEM/98_gcmsend.pm line 229, <$fh> line 184.
2017.10.11 22:25:34 1: PERL WARNING: keys on reference is experimental at ./FHEM/51_FLIC.pm line 84, <$fh> line 756.`

**Comment by ManOki** [comment]
I downloaded the current version directly from github and check via diff program, if i'm on current version. Which Pi operation system+version (i.e. rasbian stretch) are you using? which perl version do you have?

**Comment by JorinL** [comment]
Its a Raspberry Pi (one) with Raspian Jessie (8) with Perl in verison v5.20.2.

**Comment by ManOki** [comment]
As stated [here](https://perldoc.perl.org/perl5220delta.html#New-Diagnostics), from 5.22, you "Can't use a hash as a reference". 
This was deprecated before but "Versions of perl <= 5.6.1 used to allow this syntax, but shouldn't have."

**Comment by JorinL** [comment]
Well works this way even if Perl itself doesn't likes the way  it is forced to :-D

**Comment by JorinL** [comment]
OK!
Raspian Stretch and Perl 5 Version 24 - no erros but nothing works too.

`2017.10.28 02:09:32 0: Can't use a hash as a reference at ./FHEM/98_gcmsend.pm line 195, <$fh> line 189.`

**Comment by klassm** [comment]
Well you can, if you use the right url :-)
https://raw.githubusercontent.com/klassm/andFHEM/master/fhem_modules/FHEM/98_gcmsend.pm

But I'll upload a new version working on Debian Stretch shortly.

**Comment by JorinL** [comment]
Got the link from you changelog site :-) http://andfhem.klass.li/changelog/
"You will have to update the 98_gcmsend plugin by using the version **[here](https://raw.githubusercontent.com/klassm/andFHEM/master/fhem_modules/98_gcmsend.pm)**"

**Comment by klassm** [comment]
Yeah, well I had to move it later on :-)

**Comment by klassm** [comment]
Btw: the link in the docs is correct (see installation)

**Comment by JorinL** [comment]
Mh well - i fixed those errors - but the Module won't load and doesn't throw any error :-D

**Comment by klassm** [comment]
Just wait for the update :-)

Am 28.10.2017 15:56 schrieb "JorinL" <notifications@github.com>:

**Comment by JorinL** [comment]
I just try to learn ;-)

**Comment by JorinL** [comment]
Got it running! ;-)
But with 24 warnings :-D - so as you can say... quick and dirty...

**Please say me if it is a problem for you if i post my solution here - I will delete it then ;-) 
I'm just happy to got it working.** And minimal proud... for first steps.

Line 195 -> if (exists($gcmsend_encrypt_keys{$key})) {
Line 199 -> $newPayload{$key} = $cipher->encrypt_hex( $value );
Line 201 ->  %newPayload->{$key} = $value;

**Comment by JorinL** [comment]
Hehe funny completely something else like it seems :-) 

Thanks for the fix anyway :-)

**Comment by klassm** [comment]
Well not really - just some more warnings fixed at the same time :-)

... And that great (TM) Android studio 3 update, which unfortunately now
breaks the release...

Am 29.10.2017 19:19 schrieb "JorinL" <notifications@github.com>:

**Comment by JorinL** [comment]
But you did not remove the -> on if (exists($gcmsend_encrypt_keys->{$key})) 
So you did change something which I did't :D
