### ISSUE TITLE
Versioning of the 98_gcmsend.pm or integration into FHEM update mechanism

### ISSUE THREAD

**Issue by JorinL** [klassm/andFHEM#1185]
I think it would be nice to have a version number in the first line of the file or much smoother to have the file integrated into the update mechanism of FHEM - but I don't know how the connection to the FHEM'people is and how much work this affords.

**Comment by ManOki** [comment]
see #1175 and [Installation](http://andfhem.klass.li/installation/)

You can add a perl comment for versioning, but i guess this is not really necessary. You can check version here on github.

**Comment by JorinL** [comment]
But not against my local file by using my eyes :-) 
For that a simple version line would be nice.
Might be possible to do it via git - the update check - but via eyes only would be easy.

**Comment by klassm** [comment]
Please just use fhem `update check` for this issue. I do not really want to maintain another kind of versioning.

**Comment by JorinL** [comment]
So new version are coming with the update - thats a good thing to know. Thx!
