### ISSUE TITLE
FCM History Date Selection does not work properly

### ISSUE THREAD

**Issue by ManOki** [klassm/andFHEM#1188]
Hi,

i've setup the fcm part of andFHEM, i'm able to send+receive push messages via `set gcm send ticker text|my title|my text|5`.

But inside the "FCM History", the date selection does not work. Today (1.11.) if i click on the date picker icon, the 1.12. is preselected. If i select the 2.12. inside the date picker and press ok, the 2.11. is selected inside the "FCM HIstory".

Seems the month is shifted by one. The app even crashes, if i try to select the 31.12. which represent the invalid date 31.11.

Greets, ManOki

**Comment by klassm** [comment]
Thanks for reporting that issue. That's exactly an off-by-one error for months. Fixed for the next version.
Matthias
