### ISSUE TITLE
Dimmer instead of switch for fgs-223

### ISSUE THREAD

**Issue by Cyber1000** [klassm/andFHEM#1214]
I have some fibaro fgs-223 (double relais used as double light switches - http://manuals.fibaro.com/switch-2/).
In webinterface of fhem, they show right as switches with on/off buttons.
In andFHEM, they show as dimmers (though there is no dimmer within fgs-223) and I've found no way to change this beviour.
Can you help me?

Thanks!

**Comment by klassm** [comment]
Please attach an xmllist of this device. Just run 'xmllist $deviceName'
from within Fhemweb.

Thanks
Matthias

Am 26.11.2017 08:38 schrieb "Cyber1000" <notifications@github.com>:

**Comment by Cyber1000** [comment]
> <FHZINFO> 
	<ZWave_LIST> 
		<ZWave name="Licht_Wohnzimmer_Deckenfluter" state="off" sets="associationAdd associationDel dim:slider,0,1,99 dimWithDuration mcaAdd mcaDel meterReset:noArg off:noArg on:noArg stop:noArg on-till off-till-overnight intervals blink toggle off-till off-for-timer on-till-overnight on-for-timer" attrs="alias comment:textField-long eventMap group room suppressReading userReadings:textField-long verbose:0,1,2,3,4,5 IODev WNMI_delay classes disable:0,1 disabledForIntervals do_not_notify:noArg dummy:noArg eventForRaw extendedAlarmReadings:0,1,2 ignore:noArg ignoreDupMsg:noArg neighborListPos noExplorerFrames:noArg noWakeupForApplicationUpdate:noArg secure_classes showtime:noArg vclasses useMultiCmd:noArg useCRC16:noArg zwaveRoute event-on-change-reading event-on-update-reading event-aggregator event-min-interval stateFormat:textField-long timestamp-on-change-reading cmdIcon devStateIcon devStateStyle icon sortby webCmd webCmdLabel:textField-long widgetOverride userattr"> 
			<INT key="DEF" value="c732d821 2818"/> 
			<INT key="Dongle_ZWAVE_MSGCNT" value="512"/> 
			<INT key="Dongle_ZWAVE_RAWMSG" value="0004000b0c600d02013202213200000000"/> 
			<INT key="Dongle_ZWAVE_TIME" value="2017-11-26 16:02:16"/> 
			<INT key="LASTInputDev" value="Dongle_ZWAVE"/> 
			<INT key="MSGCNT" value="512"/> 
			<INT key="NAME" value="Licht_Wohnzimmer_Deckenfluter"/> 
			<INT key="NR" value="58"/> 
			<INT key="STATE" value="off"/> 
			<INT key="TYPE" value="ZWave"/> 
			<INT key="ZWaveSubDevice" value="yes"/> 
			<INT key="endpointParent" value="Hauptnode_Licht_Wohnzimmer"/> 
			<INT key="homeId" value="c732d821"/> 
			<INT key="isWakeUp" value=""/> 
			<INT key="nodeIdHex" value="0b02"/> 
			<INT key="IODev" value="Dongle_ZWAVE"/> 
			<ATTR key="IODev" value="Dongle_ZWAVE"/> 
			<ATTR key="classes" value="ZWAVEPLUS_INFO VERSION SWITCH_BINARY ASSOCIATION ASSOCIATION_GRP_INFO MULTI_CHANNEL_ASSOCIATION METER MARK SWITCH_MULTILEVEL"/> 
			<ATTR key="room" value="Wohnzimmer"/> 
			<ATTR key="webCmd" value="on:off"/> 
			<STATE key="energy" value=" 0.44 kWh" measured="2017-11-26 15:38:50"/> 
			<STATE key="power" value=" 0 W" measured="2017-11-26 16:02:16"/> 
			<STATE key="reportedState" value="off" measured="2017-11-26 09:02:16"/> 
			<STATE key="state" value="off" measured="2017-11-26 09:02:16"/> 
		</ZWave> 
	</ZWave_LIST> 
</FHZINFO>

**Comment by klassm** [comment]
Ok here we go: andFHEM tries to determine what buttons to show. By default it will show an dim button whenever a dim slider is requested within the setList. This is the case here, so the app behaves correctly.

For cases where you want to override that behaviour, you can use specific hooks:
http://andfhem.klass.li/hooks/

What you are looking for probably is the "ToggleButton" hook.

**Comment by Cyber1000** [comment]
Thanks, that did the trick:
only once, to turn the hook on: attr global userattr toggleDevice
this line for every device: attr <device> toggleDevice true

Is somehow funny that fhemweb itself shows all lights as switches, whereas andFhem shows them as dimmers, so I have to do this for every single switch ...

But I think this more a fhem topic, perhaps some inconstistency there. Any idea what causes the "dimmer-effect"? Is it the dim in sets? Perhaps fhem needs to remove this for this special device, as there is no dimmer ...

**Comment by klassm** [comment]
Yep exactly. As soon as there is a dim attribute, andFHEM will try to show
it as dimmer.
If the device is not dimmable, it should not add a dim attribute.

Am 26.11.2017 18:26 schrieb "Cyber1000" <notifications@github.com>:

**Comment by Cyber1000** [comment]
I also asked at fhem-forum (in German): https://forum.fhem.de/index.php/topic,80178.0.html
FHEM doesn't distinguish between controlled and supported Z-Wave-Classes.
If I delete SWITCH_MULTILEVEL from classes manually, the "dim" vanishes from fhem and andfhem.

So hooks or removing of SWITCH_MULTILEVEL solves this problem. I'll close this thread therefore, thanks for your help.
