### ISSUE TITLE
Room- and device list not loaded

### ISSUE THREAD

**Issue by cyberman54** [klassm/andFHEM#1230]
After today's (03.12.17) Google Play app updates my andfhem app does no longer load rooms and devices when starting, so is totally unusable :-(

**Comment by klassm** [comment]
Well... What happens if you do a manual update? What does it say? Can you
send an app log (from within the preferences) after device list update?
I'll have a look at it tomorrow ...

Am 03.12.2017 21:41 schrieb "Cyberman" <notifications@github.com>:

**Comment by cyberman54** [comment]
Manual update does not work, too, not for room list, and not for device list.

I’ve sent app log from app.

 

Von: Matthias Klass [mailto:notifications@github.com] 
Gesendet: Sonntag, 3. Dezember 2017 22:01
An: klassm/andFHEM
Cc: Cyberman; Author
Betreff: Re: [klassm/andFHEM] Room- and device list not loaded (#1230)

 

Well... What happens if you do a manual update? What does it say? Can you
send an app log (from within the preferences) after device list update?
I'll have a look at it tomorrow ...

Am 03.12.2017 21:41 schrieb "Cyberman" < <mailto:notifications@github.com> notifications@github.com>:

**Comment by klassm** [comment]
This should be fixed with the last version. Do you still encounter this issue?

**Comment by cyberman54** [comment]
Works now. Issue can be closed.
