### ISSUE TITLE
4.8.9 rooms empty/app is locked

### ISSUE THREAD

**Issue by curzon01** [klassm/andFHEM#1257]
Since update to 4.8.9 app is unusable:
- widgets are damaged (shows in green with "on" value)
- rooms are empty and can not be updated, "no rooms found" msg still present also after update
- choose "Favorites" or "All devices" blocks the app, it can only be killed

Same on two different Android devices, a Huawei Smartphone and a Samsung Galaxy Tablet

**Comment by Whisprin** [comment]
On my phone the apps screen is completely black. After some time I get the app is not responding dialog.
Clearing data and reinstalling the app didn't help.

Sony XZ1 Compact with Android 8

**Comment by klassm** [comment]
Yes, I am currently looking into this issue. Unfortunately, this is an issue only occurring for the release version of the app - thus, not occurring in development ...

**Comment by klassm** [comment]
I'll release a fix asap. Maybe you can report back as soon as it its out whether this works for you or not.

**Comment by ManOki** [comment]
I can confirm, that the newest google playstore release (version 4.9.0) works out for me. I got the same problems yesterday.

**Comment by curzon01** [comment]
confirm 4.9.0 works pretty good like pre-previous 4.8.8 - thx
