### ISSUE TITLE
Geräte verschwinden und tauchen erst nach Refresh wieder auf.

### ISSUE THREAD

**Issue by Ivo924** [klassm/andFHEM#1258]
Hallo,
AndFhem vergisst immer wieder unterschiedliche Geräte und diese tauchen erst nach einem Refresh wieder auf.
Dabei ist es egal ob ich Favoriten, Räume oder Alle Geräte aufrufe.
Widgets reagieren entsprechend nicht auf Betätigung.

Version 4.9.0 Premium
Ich hatte das Problem aber auch schon mit früheren Versionen.

Hoffe ich ist das kein Diplukat. Gefunden habe ich zumindest nichts was dem Fehler entspricht.

**Comment by klassm** [comment]
Hi,

Dafür liegt gerade lokal bei mir schon ein Fix Rum, der wohl auch
funktioniert. Ich gucke Mal ob ich das nächste Woche Release (ich muss nur
Zeit finden...).

Matthias

Am 20.01.2018 20:04 schrieb "Ivo924" <notifications@github.com>:

**Comment by Ivo924** [comment]
Hammer😎😎! Also doch ein Duplikat?

**Comment by klassm** [comment]
Naja ein Duplikat ohne Ticket. Ich komme nur vor dem Wochenende nicht dazu einen Release zu bauen ...

**Comment by Ivo924** [comment]
Hihi, ist kein Problem! Danke schon mal!

**Comment by Ivo924** [comment]
Läuft nun wunderbar. Danke!
