### ISSUE TITLE
GCM / FCM empfängt scheinbar keine Nachrichten

### ISSUE THREAD

**Issue by Ivo924** [klassm/andFHEM#1259]
AndFhem scheint die Nachrichten von FHEM nicht zu empfangen oder zumindest zu ignorieren.
Sie tauchen weder in der Historie auf, noch werden die Widgets aktualisiert wenn sie von einem anderen Gerät geschaltet werden. 
Andfhem registiert sich auch korrekt in FHEM.

Die Nachrichten gehen von FHEM korrekt raus, da EgiZone die Nachrichten empfangen kann.
Version 4.9.0 Premium

Gerne liefere ich mehr Infos wenn benötigt!

**Comment by klassm** [comment]
Ist das Gerät auch wirklich registriert, d.h. zeigt das GCM Gerät auch an,
dass das Handy registriert ist?

Stimmt die Projektnummer in den Einstellungen?

Am 20.01.2018 20:11 schrieb "Ivo924" <notifications@github.com>:

**Comment by Ivo924** [comment]
Regids bekommt einen Eintrag bzw wird erstellt wenn ich auf Gerät registrieren drücke. Mit der selben Sender id empfängt egizone die Nachrichten ja, wenn ich die regid manuell eintrage, da egizone nicht so komfortabel wie AndFHEM ist.
Deswegen verstehe ich das nicht.
Ich habe auch probehalber auf einem frischen Raspberry alles neu aufgesetzt. Dort habe ich das selbe Verhalten.
Was ich heute Nachmittag noch testen werde, ist das Verhalten auf dem Handy meiner Frau.

**Comment by Ivo924** [comment]
Nach dem ich das FCM-Projekt gelöscht und neu erstellt habe werden manuell geschickte Nachrichten nun empfangen. Jedoch bekomme werden die Widgets nicht aktualisiert wenn sich der Status ändert.

**Comment by Ivo924** [comment]
Kann geschlossen werden, über Nacht hat es sich wohl selbst repariert... irgendiwe... funktioniert jedenfalls endlich! Danke

**Comment by klassm** [comment]
Super, danke für die Info. Ich verstehe zwar nicht warum, aber wenn es wieder auftaucht sag bitte Bescheid. Ich habe zwar gerade recht wenig Zeit, aber irgendwie werden wir das schon hinbekommen.
