### ISSUE TITLE
Attribute 'hiddenroom' is ignored

### ISSUE THREAD

**Issue by mr-p666** [klassm/andFHEM#1261]
Hej Dirk,

unfortunately I can't say how long the problem already exists, but currently the 'hiddenroom' flag is ignored.

Plz check!

**Comment by klassm** [comment]
Hi,
are you sure about that issue? I just tried to configure a hiddenroom attribute on a FHEMWEB device - the room disappears from the room list.
However, the devices within that room still appear within the "All devices" list. However, this behavior is analogue to FHEMWEB itself.
Matthias

**Comment by mr-p666** [comment]
Hej Matthias (apologize for the confusion),
yes I'm sure. Just made a FHEM update and also checked andFHEM if it's up-to-date.

The xmllist of my FHEMWEB reports amongst other things:
			`<ATTR key="hiddenroom" value="Unsorted,save,DashboardRoom,ESPEasy"/>`
But when I open andFHEM the room screen shows me following:
[https://drive.google.com/file/d/1opiWgwuAW3RCuOfK5M6Nbb8VAYxGBj0b/view?usp=sharing](url)

**Comment by klassm** [comment]
Hi.
Well, do you have only one FHEMWEB device or multiple ones? Have you tried adding the FHEMWEB qualifier within the preferences?
If you have multiple FHEMWEB devices, andFHEM has no idea which one to use. So it makes an educated guess, which might be wrong :-)
Matthias

**Comment by mr-p666** [comment]
Hej,
alright then... it's not a bug it's a feature. :-)
You're right, I have a second one deployed. Which I also need for some purposes. After removing that for testing it worked as expected.
I thought (and this could be a feature request), that andFHEM uses the entered configuration attributes to figure out which is the right one.

**Comment by klassm** [comment]
Yeah it should. So you configured andFHEM to use the attribute and still
did not work - this is definitely a bug I have to look at.

Am 25.02.2018 19:12 schrieb "mr-p666" <notifications@github.com>:

**Comment by klassm** [comment]
Ok here we go - I tried to reproduce the error, but even when using the qualifier and putting the attribute to this device, the attribute was used and rooms disappeared. So something must be different in your setup.
To find out what the app really does, I've added some more logging. Currently I am releasing a new beta version of the app (this will be 5.0.0-BETA). It would be great if you would join the beta program (see http://andfhem.klass.li/changelog/ for instructions), install the new app version, make sure that it's 5.0.0 (I've released another BETA version today), and reproduce the issue. Afterwards, please send me an application log from within the settings.
Matthias

**Comment by mr-p666** [comment]
Hej Matthias,
thank you very much for your effort.
Unfortunately I can't join the program. I always get the error:

> App für dieses Konto nicht verfügbar
> Dein Konto ist derzeit nicht zur Teilnahme am Testprogramm für diese App berechtigt.

**Comment by klassm** [comment]
Hi,
Well did you join the Google+ community before clicking on the beta program
link?
Matthias


Am 26.02.2018 01:17 schrieb "mr-p666" <notifications@github.com>:

Hej Matthias,
thank you very much for your effort.
Unfortunately I can't join the program. I always get the error:

App für dieses Konto nicht verfügbar
Dein Konto ist derzeit nicht zur Teilnahme am Testprogramm für diese App
berechtigt.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/klassm/andFHEM/issues/1261#issuecomment-368359042>, or mute
the thread

**Comment by mr-p666** [comment]
Hej Matthias,
no, I haven't, because I don't have a google+ account. ;-)
