### ISSUE TITLE
Devices are missing

### ISSUE THREAD

**Issue by curzon01** [klassm/andFHEM#1267]
Since 4.9.7 devices are completly empty, widgets are displaying 'an' and all on (green).

**Comment by Ivo924** [comment]
Kann ich bestätigen. 
Keine Geräte/Räume/Favoriten mehr vorhanden.

**Comment by klassm** [comment]
Der letzte Update dürfte das Problem reparieren. Wenn nicht, bitte nochmal Bescheid geben.
