### ISSUE TITLE
Linebreak for FCM message content

### ISSUE THREAD

**Issue by ManOki** [klassm/andFHEM#1290]
Hi,

line break `'\n'` are send escaped when using the send command. I did a small bugfix, replacing line 219 in the current 98_gcmsend.pm:

`$contentText = $parts[2] =~ s/\\n/\n/r;`

I checked this and fcm itself supports line breaks.

Greets, ManOki

**Comment by klassm** [comment]
Hi,

Sounds good. As soon as I am back from vacation I'll include this change.

Thanks
Matthias

ManOki <notifications@github.com> schrieb am Do., 21. Juni 2018, 11:35:

**Comment by klassm** [comment]
Done.

Matthias

**Comment by ManOki** [comment]
Sorry that i reply now after such a long time, but i have made a mistake. The line have to be replaced by

`$contentText = $parts[2] =~ s/\\n/\n/rg;`

The last **g** stands for globally, otherwise only the first linebreak will be replaced.

Greets, ManOki

**Comment by klassm** [comment]
Sure, I've added this one also. You should be able to just do an update and
get the changed version.

Matthias

**Comment by ManOki** [comment]
Thanks for the fast response, i was able to update :)
