### ISSUE TITLE
Widgets stop working after some time

### ISSUE THREAD

**Issue by hokascha** [klassm/andFHEM#1291]
Every couple of hours, all widgets stop working and display "on" only (switch widget) or default data (room temp, humidity). 
Work-around: open the app, tap reload, tap reload again. Weird.

**Comment by klassm** [comment]
Well I got an idea what this is (I guess this is related to energy saving
mode for more recent Android versions)
 However, I am currently on vacation, so it will take some time until I can
have a look.

Matthias

Hokascha <notifications@github.com> schrieb am Fr., 22. Juni 2018, 21:11:

**Comment by klassm** [comment]
Maybe you want to have a look at the current beta version. There have been various changes concerning widget updates.
