### ISSUE TITLE
Unable to create a new connection

### ISSUE THREAD

**Issue by strauss115** [klassm/andFHEM#1304]
Since the latest update (5.3.5) I am unable to create a new device after a fresh installation of the app. When clicking on "+" Button nothing happens. Tested with

Huawei ALE-L21
API-Level: 23
and
Nexus 7
API-Level: 25

**Comment by klassm** [comment]
Hey,

Just to verify - you are talking about the plus button in the timer feature, correct? Usually the detail page opens to create a new one.

I just tried this on a quite old device (API Level 18) and on a new one (Android 9) - on both devices the plus button worked. 

Maybe you can try two things:
* Kill the application from the application settings and restart it. Do you have the same behaviour afterwards?
* Send an app log right after clicking the plus button (just go to the preferences, where you'll find a category about error handling).

Thanks and merry christmas!
Matthias

**Comment by strauss115** [comment]
Hi Matthias,
It's not the timer feature, the issue is related to the plus button for adding a new connection / device. Nevertheless, I have tried to kill and restart the app. Unfortunately, the behaviour is the same. Please find the log attached.
Thanks for checking and merry Christmas!
Michael
[andFHEM.log](https://github.com/klassm/andFHEM/files/2704119/andFHEM.log)

**Comment by klassm** [comment]
Now I found a device with the same problem. I'll keep on trying to reproduce this...

**Comment by klassm** [comment]
I got an additional log from a different user, showing a little more information. The error which is in there was already resolved for the next beta version - as no one complained about this one, I'll try to publish this. This won't make things worse, but I am not entirely sure whether it will help. Maybe you can just try it and report back if it works. If it still does not work I'll of course look again.

**Comment by strauss115** [comment]
Hi Matthias,

thanks for the update. The non-premium version shows a warning when trying to add a second connection now. That's good.

Unfortunately, the reported issue seems not to be fixed. In order to confirm I just downloaded the premium version and tested adding a new connection using another device:

API-Level: 26
Manufacturer: HUAWEI
Model: FRD-L09
App-version: 5.3.5

When clicking on plus button nothing happens (just the animation that button was clicked). Please find the log attached. Error log was not available.
[andFHEM-2.log](https://github.com/klassm/andFHEM/files/2705375/andFHEM-2.log)
It might be important to add that I was able to setup a new device/connection using Huawei FRD-L09 and the previous version of the app. Therefore, I assume that the latest update (16.12.2018) might be causing this issue.

As it might help other users, my workaround is to export / import settings in order to setup a new connection/device. Of course this requires another device, where the required device is already created.

Hope that helps.
Michael

**Comment by strauss115** [comment]
Update: Sorry, it took Google longer to rollout update for premium version. I just installed it and adding a device worked fine on FRD-L09. I will check with the other devices and let you know.

**Comment by klassm** [comment]
Perfect thanks :-). I just wanted to ask as currently I only get positive feedback from other users.

**Comment by strauss115** [comment]
Tested with all devices and adding a new connections works fine now. Thank you very much and merry Christmas.
Michael

**Comment by klassm** [comment]
Great, thanks for the info and also merry Christmas!
