### ISSUE TITLE
Support ReadingsGroup-devices

### ISSUE THREAD

**Issue by mwllgr** [klassm/andFHEM#1323]
Hey there, it would be nice if ReadingsGroup devices were supported.
Here's an XMLLIST.

```
<FHZINFO>
	<readingsGroup_LIST>
		<readingsGroup name="RGroup.Heizung" state="Initialized" sets="visibility:toggle,toggle2,show,hide" attrs="alias comment:textField-long eventMap:textField-long group room suppressReading userReadings:textField-long verbose:0,1,2,3,4,5 disable:1,2,3 style timestampStyle commands:textField-long mapping:textField-long nameIcon:textField-long cellStyle:textField-long nameStyle:textField-long valueColumn:textField-long valueColumns:textField-long valueFormat:textField-long valuePrefix:textField-long valueSuffix:textField-long valueIcon:textField-long valueStyle:textField-long separator nolinks:1 noheading:1 nonames:1 notime:1 nostate:1 firstCalcRow:1,2,3,4 alwaysTrigger:1,2 sortDevices:1 sortFn visibility:hidden,hideable,collapsed,collapsible setList setFn:textField-long headerRows sortColumn cmdIcon devStateIcon devStateIcon:textField-long devStateStyle deviceType icon mac manufacturer model serialNr sortby webCmd webCmdLabel:textField-long widgetOverride userattr">
			<INT key="DEF" value="Heizr.Steuerung:Temp-Aussen
Heizr.Steuerung:Temp-Aussen-1h
Heizr.Steuerung:Temp-Aussen-24h
Heizr.Steuerung:Ww-Temp
Heizr.Steuerung:Hz-Temp-BasisSoll
Heizr.Steuerung:Hz-KlSteilheit
Heizr.Steuerung:Temp-Vorlauf
Heizr.Steuerung:Temp-Ruecklauf"/>
			<INT key="FUUID" value="5c433671-f33f-fbef-cfc0-2154459118cdc436"/>
			<INT key="NAME" value="RGroup.Heizung"/>
			<INT key="NR" value="102"/>
			<INT key="NTFY_ORDER" value="50-RGroup.Heizung"/>
			<INT key="STATE" value="Initialized"/>
			<INT key="TYPE" value="readingsGroup"/>
			<INT key="mayBeVisible" value="1"/>
			<ATTR key="alias" value="Uebersicht Heizung"/>
			<ATTR key="group" value="Heizung"/>
			<ATTR key="mapping" value="{
	'Temp-Aussen' =&gt; 'Aussentemperatur',
	'Temp-Aussen-1h' =&gt; 'Aussentemperatur (Stunde)',
	'Temp-Aussen-24h' =&gt; 'Aussentemperatur (Tag)',
	'Ww-Temp' =&gt; 'Warmwasser',
	'Hz-Temp-BasisSoll' =&gt; 'Basistemperatur',
	'Hz-KlSteilheit' =&gt; 'Steilheit',
	'Temp-Vorlauf' =&gt; 'Vorlauf',
	'Temp-Ruecklauf' =&gt;  'Rücklauf'
}"/>
			<ATTR key="notime" value="1"/>
			<ATTR key="room" value="Heizraum"/>
			<ATTR key="valueFormat" value="{
	'Temp-Aussen' =&gt; &quot;%.1f &amp;deg;C&quot;,
	'Temp-Aussen-1h' =&gt; &quot;%.1f &amp;deg;C&quot;,
	'Temp-Aussen-24h' =&gt; &quot;%.1f &amp;deg;C&quot;,
	'Ww-Temp' =&gt; &quot;%.1f &amp;deg;C&quot;,
	'Hz-Temp-BasisSoll' =&gt; &quot;%.1f &amp;deg;C&quot;,
	'Hz-KlSteilheit' =&gt; &quot;%.1f %&quot;,
	'Temp-Vorlauf' =&gt; &quot;%.1f &amp;deg;C&quot;,
	&quot;Temp-Ruecklauf&quot; =&gt; &quot;%.1f &amp;deg;C&quot;
}"/>
		</readingsGroup>
	</readingsGroup_LIST>
</FHZINFO>
```

Thanks!

**Comment by klassm** [comment]
Hi,

well, yes, this is an open issue for years now. Unfortunately, this is quite hard to implement:

* mapping and valueFormat can be arbitrary perl expressions. For FHEMWEB that's quite easy to implement, for andFHEM it is quite hard, as you'd need a Perl parser for it. For simple expressions it would probably work, for more complex ones it would crash. Not sure whether I want those bug reports -.-
* Design is optimized towards HTML - I mean it would be possible to embed HTML, but this would duplicate the whole logic of the module. Not sure whether I want to do this - last time I did this logic in andFHEM, it ended up in a maintenance nightmare, resulting in a much more generic design of andFHEM where I did not have to care about module specifics.

As far as I currently see it the readingsgroup module is completely optimized towards FHEMWEB. I am really not sure whether the whole implementation effort would be just worth it, especially incl. the maintenance afterwards.

What actually should happens is something like a rendered HTML as reading, that can be used to display the content in external apps. But I guess this won't happen for quite some time...

I guess this does not really help ...

Matthias

**Comment by Zadolux** [comment]
Hi Matthias,
thanks for the reply - I already thought of that as a problem.

I just don't understand why they can't just implement a web interface which suits today's web standards (e.g. no <table> for everything??) and which is responsive.
Guess we can't change that.

~ M

**Comment by klassm** [comment]
-.-
