### ISSUE TITLE
Use :textField by default if no field type is given

### ISSUE THREAD

**Issue by mwllgr** [klassm/andFHEM#1333]
Hi again,

currently, andFHEM treats fields without an input type as a :noArg field. However, FHEMWEB displays an input field.

This leads to problems because some developers do not add :textField to plain text fields.
Would there be any way to fix this?

Thanks

**Comment by klassm** [comment]
Yey, yes sure. I just changed it to be textField by default. This should only have implications for the timer view and the explicit selection of a command, so it should not break anything else.

**Comment by klassm** [comment]
I guess I'll create a new beta version for this. If you like you can try it there then:
https://play.google.com/apps/testing/li.klass.fhem
https://play.google.com/apps/testing/li.klass.fhempremium

**Comment by klassm** [comment]
Released in the beta channel.

**Comment by mwllgr** [comment]
Thank you - works as intended.
Strange thing is, "on-for-timer" shows a text field instead of a time selection now too.

I don't know if this is caused by the update, just downloaded the beta version now.

**Comment by klassm** [comment]
Yes, as far as I know this was always the case, as there is no set list type for on-for-timer on whatever. There could be of course special handling in andFHEM - but it's not in place for now.
