### ISSUE TITLE
Graph timespan - current day - not working as expected

### ISSUE THREAD

**Issue by novalisek** [klassm/andFHEM#1334]
Hi,
I am using MAX! cube + thernostats etc, I have some graphs defined and I have "Current day" selected in Preferences -> Graph timesamp.
But still when I open any MAX! graph, there is 24 hours timespan shown and I need to select Start date/time manualy to only show current day.  When I close the graph and reopen it, there is 24h timestamp again ...
When I select 12 or 48 hours (I didn't try all the options), it is working as expected ...

**Comment by klassm** [comment]
Hi,
thanks for reporting that issue. I just released a new beta app that should resolve the issue. I'll also release this to the "normal" app - but not during christmas holidays.
Matthias

**Comment by novalisek** [comment]
seems to be working fine in new version, thanks
