### ISSUE TITLE
Support for datetime picker

### ISSUE THREAD

**Issue by stephanritscher** [klassm/andFHEM#1335]
Hi there,

what would we need for supporting dummy devices with a datetime widget.
The widget is not official but committed contrib folder in SVN. Refer to: https://forum.fhem.de/index.php?topic=35736.0

My special instance is defined by
```
define HolidayPeriods dummy
attr HolidayPeriods alias Urlaubszeiten
attr HolidayPeriods readingList from:to
attr HolidayPeriods setList from:datetime,timepicker:false,format:d.m.Y to:datetime,timepicker:false,format:d.m.Y
attr HolidayPeriods webCmd from:to
attr HolidayPeriods webCmdLabel von&nbsp;;:bis&nbsp;;
attr HolidayPeriods stateFormat from - to
```
 - from:datetime means that reading from is displayed using a datetime widget; properties are separated by colon (,)
 - timepicker:false disables the time selection (so only date selection is shown)
 - similarly you can use datepicker:false to disable the date selection
 - default is to show date and time selection
 - format:d.m.Y defines the date format of the selected time; this format is also used to parse the reading when opening the datetime picker
 - default date format is "d.m.Y H:i" where
   - Y is 4 digit year
   - m is 2 digit month
   - d is 2 digit day
   - H is 2 digit hour (24 hour format)
   - i is 2 digit minutes
- step:10 may be used in order to define the interval size in minutes of selectable times (default: step:60)
- other properties like inline:true and theme:default could be ignored (not relevant for andFHEM, as far as I understand)

Has anyone considered implementing support for this? What would be needed?

Best regards,
Stephan

**Comment by klassm** [comment]
I've released a new beta version. You can test it there - certainly not the prettiest implementation, but it should work.

**Comment by stephanritscher** [comment]
Thanks a lot, especially for the really fast action on this request!
I just tested it and it works right from the start :-).

One thing I already noted for the time picker: I would find it more intuitive if the time/datetime picker was initialized to the current value of the field instead of the current time and date.
But I think that's a philosophical discussion, just my 2 cents. I'll be closing the issue and leave the usability decisions to you ;-).
