### ISSUE TITLE
Automatic switching between light and dark theme isn't working any more

### ISSUE THREAD

**Issue by mr-p666** [klassm/andFHEM#1420]
Hej Matthias,

it isn't possible to automatically switch between the light and dark theme any more while selecting one of them manually works better.
Just the menu still stays bright when select the dark theme and starting the app the first time after changing the theme.

Best regards,
   Gerhard

**Comment by klassm** [comment]
Hi Gerhard,

what Android version are you using? I just tried it with my normal Pixel device - but there I could switch between themes just normally.

Matthias

**Comment by mr-p666** [comment]
Hej Matthias,

I've tried it again on all my devices and can't reproduce the problem any more. :-)
Maybe there was a firmware update in the meantime which fixed this. Sorry for this disturbing on this issue.

**Comment by klassm** [comment]
Hey,
thanks for the info!
