### ISSUE TITLE
Timestamps are gone

### ISSUE THREAD

**Issue by mr-p666** [klassm/andFHEM#1421]
Hej Matthias,

just realized, that the timestamps of my HM-devices are gone.
eg. It was always great to see when it was the last time, the status of the window had changed in the room overview.

Plz restore old behavior or make it at least configurable.

Thx a lot!

Best regards,
Gerhard

**Comment by klassm** [comment]
Hi Gerhard,

those timestamps moved to the actual device details - to get the actual device list a little less cluttered. You should still be able to see the same information.

**Comment by klassm** [comment]
Hi Gerhard,

did you check again? Is that information sufficient for you there or do you really need it back in the list?

Matthias

**Comment by mr-p666** [comment]
Hello Matthias,
thanks for your response. Yes, I really need the information in the list.
I always use it to ensure, if the information is actual or not.

Gerhard

**Comment by klassm** [comment]
Hey ho. I'll release a new beta version where you can enable this again within the appearance app settings. Matthias

**Comment by mr-p666** [comment]
Works like a charm!
Thx a lot! :-)

**Comment by klassm** [comment]
Great, nice to hear!
