### ISSUE TITLE
Widgets in MQTT_DEVICE

### ISSUE THREAD

**Issue by Lutzion** [klassm/andFHEM#1423]
Hello Matthias,

i have defined a mqtt device in fhem:

```
define ESPTest8x1 MQTT_DEVICE
attr ESPTest8x1 IODev mqttBroker
attr ESPTest8x1 cmdIcon save:edit_save
attr ESPTest8x1 devStateIcon { ESPEasy_devStateIcon($name) }
attr ESPTest8x1 publishSet_color /I/ESP_Easy_3/LEDs/Color
attr ESPTest8x1 publishSet_dim /I/ESP_Easy_3/LEDs/Brightness
attr ESPTest8x1 publishSet_rgb /I/ESP_Easy_3/LEDs/Color
attr ESPTest8x1 publishSet_save /I/ESP_Easy_3/LEDs/Save
attr ESPTest8x1 publishSet_type /I/ESP_Easy_3/LEDs/Type
attr ESPTest8x1 publishSet_fxs /I/ESP_Easy_3/LEDs/FxSpeed
attr ESPTest8x1 room ESPEasy
attr ESPTest8x1 stateFormat state
attr ESPTest8x1 subscribeReading_color /O/ESP_Easy_3/LEDs/Color
attr ESPTest8x1 subscribeReading_dim /O/ESP_Easy_3/LEDs/Brightness
attr ESPTest8x1 subscribeReading_rgb /O/ESP_Easy_3/LEDs/Color
attr ESPTest8x1 subscribeReading_type /O/ESP_Easy_3/LEDs/Type
attr ESPTest8x1 subscribeReading_fxs /O/ESP_Easy_3/LEDs/FxSpeed
attr ESPTest8x1 webCmd rgb:dim:fxs:type:save
attr ESPTest8x1 widgetOverride rgb:colorpicker,RGB color:colorpicker,RGB dim:slider,0,1,255 fxs:slider,0,1,1024 type:select,0,1,2,3,4,5,6,7,8
```

in FHEM i get all the controls defined in widgetOverride. An RGB Control, 2 sliders and one dropdown list.
![FhemMqttTest8x1](https://user-images.githubusercontent.com/46639828/86473843-f1793d80-bd41-11ea-813a-bdef1d7502b4.png)

in **andFHEM** i just get inputboxes to enter the values.

![andFHEM_Mqtt2](https://user-images.githubusercontent.com/46639828/86474381-fe4a6100-bd42-11ea-9854-0e30215b73e7.jpg)

Is it possible to get the widgets like for example in ESPEasy ?

All the best, Lutz

**Comment by klassm** [comment]
Well those widgets work based on the setList attributes you have. So if you are able to get an off / on attribute in your setList, you'll probably also get a on/off widget automatically there.

**Comment by klassm** [comment]
Closed due to missing input.

**Comment by Flattermann78** [comment]
The MQTT_DEVICE does not feature a setList. The closest thing is a publishSet_* but has a different meaning ...
