### ISSUE TITLE
andFHEM without Google Play-Services

### ISSUE THREAD

**Issue by marvinwankersteen** [klassm/andFHEM#1424]
Hey,

I would like to reinstall LineageOS without GAPPS and I am testing some apps if they will work.
I receive continuously the message `andFHEM only works after the Google Play services have been activated.`

How can I use andFHEM with disabled Google Play-Services?

Edit*
Okay, it looks like andFHEM works although the message appears. Does andFHEM necessarily require the installed play services?

**Comment by klassm** [comment]
Yes, usually andFHEM requires play services - it would be quite a bunch of work to separate all the dependencies to get rid of it (actually I never tried whether it works without Play Services ....) :-)

**Comment by marvinwankersteen** [comment]
I have now installed LineageOS without GAAPS and andFHEM is working. I simply disabled the hint in the notification bar.
