### ISSUE TITLE
Cannot access files on Android 11 device

### ISSUE THREAD

**Issue by zilon84** [klassm/andFHEM#1472]
Hello,

I typically use clientcertificates to access FHEM and up to Android 10 this works pretty well. On an Android 11 device, I am not able to configure andFHEM touse the client cert because I have no/only limited file access from the andFHEM user interface.

Permissions to access files have been granted to andFHEM but the issue is still there. The only folders I can see in the andFEHM file manager are named "asec" and "obb". Both folders are empty.

Thanks and best regards,
Zilon

**Comment by klassm** [comment]
Hey, sorry I didn't see that issue for quite some time and stumbled upon it today. There's an open issue about this also in the underlying library, so I swapped that one now. I'll release a new beta version when the build completes successfully. Maybe you can have a look then.
Matthias

**Comment by zilon84** [comment]
Hello,
thank you for providing the beta version. File browsing in general is now possible, but I observed the limitation that only PNG and JPG files are visible. So I still can't use the P12 file with the client cert.

Thank you and BR
Zilon

**Comment by klassm** [comment]
That's a strange thing - it seems like Android deprecated some APIs - which now results in only images being shown. Weird. I changed it to scoped storage now and will release another version ....

**Comment by klassm** [comment]
And another beta version ...

**Comment by klassm** [comment]
@zilon84 Did you have a chance to try it out one more time?

**Comment by zilon84** [comment]
Hello,

yes I was able to successfully test the new version. I can access the client cert and use it with andFHEM.

The only strange thing that occurs after some time is that the app seems to lose the ability to use the cert. In the administration menu of andFHEM everything seems to be OK. There is still a path to the cert written. Anyhow, I have to add the cert again and everything is working fine again.

Does andFHEM store a copy of the cert? Maybe this copy is deleted due to some cleanup routine of Android. After the cert is added again this copy is on its place and the app works.

Thanks and BR
Zilon

**Comment by klassm** [comment]
Hi @zilon84 ,

No it doesn't. However, Android 11 changed the storage implementation, so you cannot access files any more. Don't ask me why, but now everyone has to adapt.
What I did now is load the certificate to the andFHEM connection and save it internally. This should probably make it work again, as now there's only one time loading the file - which is directly after selecting it in the file picker. However, most probably this means that you will have to reselect the certificate again.
I will release another beta version and hopefully it fixed the issue. Unfortunately I don't have a client certificate configured here. So I am doing my best on guessing how it could work ....
Matthias

**Comment by klassm** [comment]
After some weird issues, there's now a new Beta version. Maybe you can have a look again.

**Comment by zilon84** [comment]
So, I just checked the new beta version.

Changed behavior ist the following: After selecting the cert with the file picker, it ssems to be imported into andFHEM. At the location where typically the path to the cert is displayed, I now see many weird characters and symbols.

Access to the FHEM system is no longer possible.

**Comment by zilon84** [comment]
The latest beta seems to solve the issue. Even after a restart of the device the app is still able to login via the client cert. 
Thank you!

**Comment by klassm** [comment]
Cool, thanks for the info :-). That was basically the last try - now to copy the certificate from your location to an andFHEM internal location - and read it from the file when doing a request.
I'll give it some more time though whether it really works.
