### ISSUE TITLE
Publish on FDroid

### ISSUE THREAD

**Issue by sepo83** [klassm/andFHEM#1555]
Would be greate if andFHEM could be also published on FDroid.

You can find some information how to do that [here](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md) and [here](https://f-droid.org/en/docs/Inclusion_Policy/). I would also offer some help, if you like.

EDIT:
I have just seen that it already published there, but in a very old version (Version 2.4.1). Is there a reason why not to update?

**Comment by klassm** [comment]
See #1561
