### ISSUE TITLE
Can't edit/save/create new connections in andFHEM

### ISSUE THREAD

**Issue by JorinL** [klassm/andFHEM#1690]
Since the latest update (using the beta 6.3.9-BETA tree in playstore - android) I can't edit/view or create and save a connection to my server :-)

- Save button when creating a new one - does not close the ui or works at all.
- Editing the existing connection shows an empty dialog like creating a new one.

**Comment by JorinL** [comment]
@klassm is it a workaround to switch to the stable branch ;-) ?
Or can you provide me one?

Killing all widgets on three screens is painful :-D

**Comment by klassm** [comment]
Sorry for the bug - there's a new beta version on its way. Maybe you can give some feedback whether it works for you using the new version.

**Comment by JorinL** [comment]
Sure - will do as soon as available :-)
Thanks.

**Comment by JorinL** [comment]
Fixed! 

Thanks!
