### ISSUE TITLE
[Beta] Widgets do not refresh after using "Update device list" widget - also when being inside the app and updating the room

### ISSUE THREAD

**Issue by JorinL** [klassm/andFHEM#1691]
My widgets do not refresh - not using "Update device list" widget, but also when being inside the app and updating the room.
(using the beta 6.4.0-BETA tree in playstore - android)

Is there something broken :-) ?

**Comment by klassm** [comment]
Hi Jorin,
I just tried it - the widget updates when I switch in FHEM, refresh the device list and look at the widget. Are you doing something different?

**Comment by JorinL** [comment]
Hey Matthias,
on my S20+ it does not refresh the Widgets at all.
Having my Fan switched on in the widget - makes it go green. Also switching off - turns it off.
But switching inside the app  or switching it somehow else so that FHEM gets info about it and then pressing the widget "refresh devices" or being inside andFHEM and refreshing the Room does not change the widget on the homescreen - it stays on or off (state it had before switching somewhere else)

I could make you a screen recording.

**Comment by klassm** [comment]
Well the update mechanism of clicking on the widget and clicking within takes the same route to update the widget. This points to _some_ weirdness. I have a bad feeling about this - those issues seem to always happen on Samsung phones. It also does not seem to be a general issue - then more people would complain about that issue.
What you could do 
* You could add andFHEM to the energy saving exclusions (https://dontkillmyapp.com/samsung). This is a very typical issue that prevents the app from updating.
* You could actually reproduce the issue and then send a log from the andFHEM settings - maybe that will show up some more information.

What happens by the way when you readd the widget?

**Comment by JorinL** [comment]
Hey :-)

"What happens by the way when you readd the widget?"
What? :-D

**Comment by klassm** [comment]
Readd in the sense of deleting it and adding it again. Does that change the behaviour?

**Comment by JorinL** [comment]
Okay...... damn I've could tested that by myself :D
Fixed it to delete and again set it up.

**Comment by klassm** [comment]
Not sure why it broke in the first place though. Let's see when it happens
again.

JorinL ***@***.***> schrieb am So., 12. Sept. 2021, 19:00:
