### ISSUE TITLE
[Beta] When placing a 1x1 widget and choosing  "other"

### ISSUE THREAD

**Issue by JorinL** [klassm/andFHEM#1692]
Hey :-)
When placing a widget and choosing 1x1 and then the tab "other" (from device-widget, room-widgets, other) andfhem crashes.
On S20+ and S8.
Is ist my FHEM installation or a bug in the beta?

**Comment by elhennig** [comment]
Same here on my LG V30 A11 PE+ mobile

**Comment by klassm** [comment]
Thanks for the heads up, will release a new beta probably today 🙏

**Comment by elhennig** [comment]
Works again with latest Beta. Thanks for the quick fix!

**Comment by JorinL** [comment]
Jip works. :-)
