### ISSUE TITLE
android 14 - blank app

### ISSUE THREAD

**Issue by binlan** [klassm/andFHEM#2067]
since android 14 update the app didnt load anymore. It hangs with a blank screen just showing the logo. Existing Widgets still works. But new one cant be created.

binlan

**Comment by burn79** [comment]
same problem here

**Comment by cyberman54** [comment]
Same here. Renders app as unusable :-(

**Comment by klassm** [comment]
That's a breaking change in Android 14. I do not use the app anymore myself, so it takes ages until someone notes. In the end, it becomes more and more clear the app will vanish soonish. Anyways, I've pushed a fix.

**Comment by binlan** [comment]
> I do not use the app anymore myself
may i ask, what you are using instead? or isnt fhem at all not your platform anymore?
> Anyways, I've pushed a fix.
thx, for that. will test it when its arrived the playstore.

**Comment by klassm** [comment]
I am only using HomeMatic devices, plus some ZigBee and by now Matter Thread devices. When I only had HomeMatic some years ago, I completely switched over to HomeAssistant.

**Comment by burn79** [comment]
> That's a breaking change in Android 14. I do not use the app anymore myself, so it takes ages until someone notes. In the end, it becomes more and more clear the app will vanish soonish. Anyways, I've pushed a fix.

works again, thanks!

**Comment by cyberman54** [comment]
I am using AndFHEM Premium. I don't see an update in Google Play Store yet?

**Comment by cyberman54** [comment]
Premium Update received today. App works again! Thank you!
I think this issue can be closed now.
