### ISSUE TITLE
Android 14 - Werte aktualisieren nicht möglich

### ISSUE THREAD

**Issue by burn79** [klassm/andFHEM#2071]
Hallo,

dank Patch https://github.com/klassm/andFHEM/commit/b084c775f0db5c2e8c71e9e6b788bbf4e24ea398 startet andfhem auf Android 14 glücklicherweise wieder. 👍 
Beim Programmstart werden auch alle Werte aus fhem gelesen. Die Werte lassen sich bei geöffneter App aber nicht mehr aktualisieren. Beim Tippen auf die beiden kreisförmig angeordneten Pfeile oben rechts passiert nichts, auch keine drehende Animation der Pfeile.
Bei der aktualieren Geste (Bildschirm nach unten ziehen) erscheint zwar ein sich drehender Kreis, aber dieser dreht sich dauerhaft, ohne dass Werte neu geladen werden.
Wenn dieser Fehler bitte noch behoben werden könnte @klassm ?

![Screenshot (17 10 2023 08 51 44)](https://github.com/klassm/andFHEM/assets/25819251/faf3988d-2b05-4a6b-becf-cb1e0cd6a340)

**Comment by klassm** [comment]
There seems to be a way to make this work still, so I pushed another fix. However, all of this uses deprecated APIs in Android - even the fix. To properly fix this most of the app would have to be rewritten.
