### ISSUE TITLE
Export-/Importfunktion

### ISSUE THREAD

**Issue by mr-p666** [klassm/andFHEM#783]
Hej Matthias,

gab es schon einmal eine Anfrage für eine Export-/Importfunktion?
Wäre toll, wenn man sämtliche Daten als File exportieren könnte und nicht immer wieder alles hineinklopfen müsste. Habe fünf Verbindungen hinterlegt und die jedesmal auf jedem Telefon wieder eingeben ist recht mühsam. ;-)

Thx a lot!

**Comment by klassm** [comment]
Soderla - das kommt in der nächsten Version.

In den Einstellungen gibt es dazu zwei Knöpfe - Export und Import. Während des Export-Vorgangs kann man auch ein Passwort zur Verschlüsselung angeben. Sonst steht im Backup im Klartext das Verbindungspasswort zu deiner FHEM Instanz.

Backups liegen jeweils in Documents/andFHEM/*

Die Funktionalität gibt es nur für Android 4 und aufwärts.
