### ISSUE TITLE
Support PID20

### ISSUE THREAD

**Issue by mrandt** [klassm/andFHEM#880]
Hello,
as the recommended P-I-D implementation in FHEM has changed from module PID to module PID20, it would be great if one could see and control such modules in andFHEM app.

I think it would be good to view `desired`, `measured`, `delta`, `state` and `actuation`.

The values I would like to change are `desired` and `state` (stop, start).

See excerpt from XMLLIST below:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<FHZINFO>
   <PID20_LIST>
      <PID20 name="eg.wohnen.pid" state="processing" sets="stop:noArg start:noArg restart desired" attrs="verbose:0,1,2,3,4,5 room group comment alias eventMap userReadings pidActorValueDecPlaces:0,1,2,3,4,5 pidActorInterval pidActorTreshold pidActorErrorAction:freeze,errorPos pidActorErrorPos pidActorKeepAlive pidActorLimitLower pidActorLimitUpper pidCalcInterval pidDeltaTreshold pidDesiredName pidFactor_P pidFactor_I pidFactor_D pidMeasuredName pidSensorTimeout pidReverseAction pidUpdateInterval pidDebugSensor:0,1 pidDebugActuation:0,1 pidDebugCalc:0,1 pidDebugDelta:0,1 pidDebugUpdate:0,1 pidDebugNotify:0,1 disable:0,1 event-on-change-reading event-on-update-reading event-min-interval stateFormat DbLogExclude devStateIcon devStateStyle device_timeout fp_EG icon sortby webCmd widgetOverride userattr">
         <INT key="DEF" value="eg.wohnen.gesense:T0:([\d\.]*) eg.wohnen.stellantrieb.01:valve" />
         <INT key="NAME" value="eg.wohnen.pid" />
         <INT key="NR" value="69" />
         <INT key="NTFY_ORDER" value="50-eg.wohnen.pid" />
         <INT key="STATE" value="processing" />
         <INT key="TYPE" value="PID20" />
         <ATTR key="alias" value="PID Regelung Wohnzimmer Fenster" />
         <ATTR key="icon" value="icoTool" />
         <ATTR key="room" value="Wohnzimmer" />
         <STATE key="actuation" value="27" measured="2015-02-22 17:18:47" />
         <STATE key="actuationCalc" value="26.8124999999982" measured="2015-02-22 17:20:47" />
         <STATE key="delta" value="0.129999999999999" measured="2015-02-22 17:20:47" />
         <STATE key="desired" value="21.5" measured="2015-02-22 17:18:47" />
         <STATE key="measured" value="21.37" measured="2015-02-22 17:18:47" />
         <STATE key="p_d" value="0" measured="2015-02-22 17:20:47" />
         <STATE key="p_i" value="23.5624999999982" measured="2015-02-22 17:20:47" />
         <STATE key="p_p" value="3.24999999999998" measured="2015-02-22 17:20:47" />
         <STATE key="state" value="processing" measured="2015-02-22 17:20:47" />
      </PID20>
   </PID20_LIST>
</FHZINFO>
```

Thanks and best regards
Malte

**Comment by klassm** [comment]
Hi Malte,

are you, by chance, developer of this module? If so, could you add a proper setList attribute for desired? This is usually a slider attribute, like so: desired:slider,0,1,100

What's the normal range for the desired attribute? Does it range between 5.5 and 30 (like FHT devices?)

Matthias

**Comment by mrandt** [comment]
Hi Matthias,

not sure about your native language but we could communicate in German 
if that makes life easier ;-)

Anyways, thanks for your message. I am not the developer of said module, 
just an FHEM user who recently upgraded and found that the old PID was 
being deprecated and PID20 was the way forward...

I checked the source but found no author credits. According to the 
current list of FHEM maintainers, "John" is responsible:
http://fhem.de/MAINTAINER.txt

The user who last cheked in the module was called "john99sr" - 
unfortunately I do not have a complete name or e-mail address I could 
point you to. Maybe just reach out to the main developer Rudolf König 
(r.koenig@koeniglich.de)? He can probably get you in touch with John as 
PID20 is part of the official FHEM distribution.

Regarding the attribute "desired": This actually represents the desired 
target temperature in degrees centigrade. So a slider from 15 to 25 and 
0.5 step probably makes sense, otherwise a numeric input would do.

Good luck and thank you for your efforts!

Malte

Am 01.03.2015 um 13:57 schrieb klassm:
>
> Hi Malte,
>
> are you, by chance, developer of this module? If so, could you add a 
> proper setList attribute for desired? This is usually a slider 
> attribute, like so: desired:slider,0,1,100
>
> What's the normal range for the desired attribute? Does it range 
> between 5.5 and 30 (like FHT devices?)
>
> Matthias
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/klassm/andFHEM/issues/880#issuecomment-76595646>.
>

  
--
Grizzly Engineering
Malte Randt
Sindlinger Strasse 10-4
71131 Jettingen
malte.randt@grizzly-engineering.com
www.grizzly-engineering.com
