### ISSUE TITLE
NullPointerException when saving config

### ISSUE THREAD

**Issue by JasonMask** [klassm/andFHEM#886]
Hi

im not quite sure how to reproduce this so i'll try to remember what i can.

i have been using the free version before and everything was fine.
then i bought the premium app yesterday (from the store, not in-app).
i got the message that i shouldn´t have both installed at the same time so i uninstalled the free version.
there through  i guess i lost the settings from the free version an wanted to set them up in the premium version again.
when trying this nothing happens when i hit the save button (regardless how often).
so i tried to go back to the free version by uninstalling premium and reinstalling the free version.
now the free version does show the same behaviour and i can´t use the app anymore.

to me it looks like there is an initial config missing.

github wouldn´t let me upload the log as .log file so i renamed it to .gif. i hope this will workout.
![andfhem--1572076684](https://cloud.githubusercontent.com/assets/11296381/6465202/d0b88412-c1bf-11e4-80fc-4f001b5c3f12.gif)

thanks for fixing this soon or telling me a workaround

cu & thx jason

**Comment by klassm** [comment]
Fixed with #888

**Comment by JasonMask** [comment]
works like a charm

thank you
