### ISSUE TITLE
support Lan- and Wan-URL for Settings

### ISSUE THREAD

**Issue by JasonMask** [klassm/andFHEM#887]
Hi,

i currently (right before everything stopped working due to #886) face the issue that my router doesn´t support dns loopback and therefor i am not able to access my fhem server from within my lan when using my dyndns name.
access works fine when using the local ip or having my phone not connected to the lan.

could you please offer two (or maybe even n) input fields for server url´s where the second(/later) urls are tried when the first wasn´t reachable? if this isn´t suitable you could also check if the device that runs andfhem does have an ip from an private address space (i´m using the 10.x.x.x space so please don´t limit it just to the 192.168.x.x space (and don´t forget that 172.16.x.x space while you´re on it ;) ))

thank you

cu jason

**Comment by klassm** [comment]
Hi Jason,

I'll be clear about my opinion towards that issue. Of course you can disagree and I'll of course give you a chance to issue your arguments but - I for myself treat the opinion that this is not an issue that should be solved by any application.

As you are describing - this is a network configuration issue. And it should be solved on that level. A server has exactly one URL - and not many ones.

In every case - have you ever seen an Android app (or any other application) offering the opportunity to enter multiple server URLs? This will disconcert 99% of all users - and have use for at most the 1%.

Considering the priority of other tasks (even within this issue tracker) this will be at most a low priority task.

Sorry,
Matthias

**Comment by JasonMask** [comment]
Hi Matthias,

i wont argue with you about how f** up that easybox 904 is (it worked with the older one but that wont give me vdsl...) and that the problem should be solved there, but the openhab app does support this ;) https://play.google.com/store/apps/details?id=org.openhab.habdroid

oh well i guess i´ll argue a bit at least: easybox 904 is the router provided by vodafone germany for their vdsl clients so there might be quit a userbase.

i guess regular users wont but i could probably solve this by running my own dhcp and dns server in my network but i realy realy realy dont want to set all that up (mostly because it would install one more single point of failure into my network)

i hopped it would be a quick win that could be handy to more users then me (could be a premium feature ;) ).

thanks anyway

cu jason
