### ISSUE TITLE
Support TCM97001

### ISSUE THREAD

**Issue by klassm** [klassm/andFHEM#895]

**Comment by michaelwingender** [comment]
Hi,
Should this device type be already recognised by andFHEM? In my App devices do not show up. Following one example xmllist
<CUL_TCM97001 name="Mebus_95" state="12.6&amp;deg;C&lt;BR&gt;" sets="" attrs="alias comment:textField-long eventMap:textField-long group room suppressReading userReadings:textField-long verbose:0,1,2,3,4,5 IODev do_not_notify:1,0 ignore:0,1 showtime:1,0 event-aggregator event-min-interval event-on-change-reading event-on-update-reading oldreadings stateFormat:textField-long timestamp-on-change-reading max-deviation-temp:1,2,3,4,5,6,7,8,9,10,15,20,25,30,35,40,45,50 model:ABS700,AURIOL,Eurochron,GT_WT_02,KW9010,Mebus,NC_WS,PFR_130,Prologue,Rubicson,TCM21....,TCM97...,Type1,Unknown,W044,W132,W174 DbLogExclude DbLogInclude DbLogValueFn:textField-long assistantName:textField cmdIcon devStateIcon devStateIcon:textField-long devStateStyle fp_Home gassistantName:textField genericDeviceType:security,ignore,switch,outlet,light,blind,thermometer,thermostat,contact,garage,window,lock,aircondition,airpurifier,camera,coffeemaker,dishwasher,dryer,fan,kettle,oven,refrigerator,scene,sprinkler,vacuum,washer,airfreshener,blinds,fireplace,heater,awning,boiler,curtain,door,gate,hood,microwave,pregola,securitysystem,shutter,shower,valve,waterheater,ac_unit,bathtub,bed,blender,closet,coffee_maker,cooktop,dehumidifier,dehydrator,drawer,faucet,fryer,grill,humidifier,mop,mower,multicooker,pergola,petfeeder,pressurecooker,radiator,sousvide,standmixer,yogurtmaker homebridgeMapping:textField-long icon onOffDevice:true,false realRoom:textField sortby webCmd webCmdLabel:textField-long widgetOverride widget_name userattr">
			<INT key="CHANGED" value=""/>
			<INT key="CODE" value="CUL_TCM97001_95"/>
			<INT key="CUL_MSGCNT" value="13252"/>
			<INT key="CUL_RAWMSG" value="sE5F07E603B;  432: 9568"/>
			<INT key="CUL_TIME" value="2020-02-23 11:54:36"/>
			<INT key="DEF" value="CUL_TCM97001_95"/>
			<INT key="FUUID" value="5e232edd-f33f-cfec-1372-9fdcccbc155ff659"/>
			<INT key="LASTInputDev" value="CUL"/>
			<INT key="MSGCNT" value="13252"/>
			<INT key="NAME" value="Mebus_95"/>
			<INT key="NR" value="830"/>
			<INT key="RSSI" value="-44.5"/>
			<INT key="STATE" value="12.6&amp;deg;C&lt;BR&gt;"/>
			<INT key="TYPE" value="CUL_TCM97001"/>
			<INT key="lastH" value="0"/>
			<INT key="lastT" value="1582455276.4814"/>
			<ATTR key="event-min-interval" value=".*:300"/>
			<ATTR key="event-on-change-reading" value=".*"/>
			<ATTR key="group" value="Temperatur"/>
			<ATTR key="icon" value="temp_outside"/>
			<ATTR key="model" value="Mebus"/>
			<ATTR key="room" value="Balkon,CUL_TCM97001"/>
			<ATTR key="stateFormat" value="temperature&amp;deg;C&lt;BR&gt;"/>
			<STATE key="battery" value="ok" measured="2020-01-18 17:14:57"/>
			<STATE key="batteryState" value="ok" measured="2020-01-18 17:14:57"/>
			<STATE key="channel" value="1" measured="2020-01-18 17:14:57"/>
			<STATE key="mode" value="normal" measured="2020-01-18 17:14:57"/>
			<STATE key="state" value="T: 12.6" measured="2020-02-23 11:54:36"/>
			<STATE key="temperature" value="12.6" measured="2020-02-23 11:54:36"/>
		</CUL_TCM97001>

**Comment by klassm** [comment]
Hi,

not sure, but I just tried your xmllist. It shows up as Mebus_95 as temperature device. Seems right to me.

Matthias
