### ISSUE TITLE
MAX HeatingThermostatPlus Timetable change widget has broken layout

### ISSUE THREAD

**Issue by johol545** [klassm/andFHEM#909]
When editing a timetable entry for a MAX HeatingThemostatPlus the temperature input control is not always visible.

**Steps to reproduce:**
1. Open a _MAX HeatingThemostatPlus_ device
2. Click the _Timetable_ button at the bottom of the page
3. Click a _change_ button

**Expected result:**
Temperature slider is visible

**Actual result:**
Temperature slider is hidden below footer bar containing _OK_ button
<img src="https://cloud.githubusercontent.com/assets/933461/7345727/686ebe22-eccf-11e4-9e3c-2562326d90d2.png" width="50%">

**Workaround:**
1. Open a _MAX HeatingThemostatPlus_ device
2. Click the _Timetable_ button at the bottom of the page
3. Rotate screen to landscape
4. Click a _change_ button
<img src="https://cloud.githubusercontent.com/assets/933461/7345764/f141d9a0-eccf-11e4-9177-f85dad2443c2.png" width="50%">
5. Rotate screen to portrait mode.
<img src="https://cloud.githubusercontent.com/assets/933461/7345779/0e349b88-ecd0-11e4-8eb0-682966c91ee8.png" width="50%">

**Platform:**
* **Device:** Nexus 5
* **Android version:** 5.1
* **AndFHEM version:** 3.5.1

**Comment by klassm** [comment]
Well - that's a nice one... especially because Google's timepicker behaves differently after switching back to portrait mode. I can't change that one, but I've added a scroll view to make the temperature slider accessible again.

**Comment by johol545** [comment]
Yeah, isn't it nice! :-)

Thanks for fixing this one and all your efforts with the product in general!
