### ISSUE TITLE
custom_graph not longer shown (for CUL_WS)

### ISSUE THREAD

**Issue by psytester** [klassm/andFHEM#913]
Since about  one month andFHEM does not longer show the customGraphs for my CUL_WS devices.

Setting are:
`
attr global userattr custom_graph1 custom_graph2 custom_graph3 custom_graph4 custom_graph5 custom_graph6 devStateIcon devStateStyle icon sortby webCmd

# -----  Definiton of Kellertreppe
define CUL_WS_KellerTreppe CUL_WS 1
attr CUL_WS_KellerTreppe room CUL_WS

define FileLog_CUL_WS_KellerTreppe FileLog ./log/CUL_WS_KellerTreppe-%Y.log CUL_WS_KellerTreppe:T:.*
attr FileLog_CUL_WS_KellerTreppe custom_graph1 8:D:@°C@Taupunkt
attr FileLog_CUL_WS_KellerTreppe custom_graph2 10:A:@g/m³@absFeuchte
attr FileLog_CUL_WS_KellerTreppe logtype temp4hum6:Temp/Hum,text
attr FileLog_CUL_WS_KellerTreppe room CUL_WS

define KellerTreppe_Temp2Hum6Dew8AbsF10 SVG FileLog_CUL_WS_KellerTreppe:temp4hum6innen:CURRENT
attr KellerTreppe_Temp2Hum6Dew8AbsF10 label "KellerTreppe Temp-Min $data{min1}, Max $data{max1}, Last $data{currval1}, relFeuchte-Min: $data{min2}, Max: $data{max2}, Last: $data{currval2}"
attr KellerTreppe_Temp2Hum6Dew8AbsF10 room Plots

define KellerTreppe_Hum6Abs10 SVG FileLog_CUL_WS_KellerTreppe:hum6abs10innen:CURRENT
attr KellerTreppe_Hum6Abs10 label "KellerTreppe Hum-Min $data{min1}, Max $data{max1}, Last $data{currval1}, absFeuchte-Min: $data{min2}, Max: $data{max2}, Last: $data{currval2}"
attr KellerTreppe_Hum6Abs10 room Plots
`

**Comment by klassm** [comment]
Hi,

thanks for that info. However, I suppose I will not fix this bug, as custom_graphs (and log definitions in general) within andFHEM will be kicked out in the next version and replaced by GPlot definitions, which is the much more general approach.

Still I'll leave the bug open until the Gplot version is released.

Matthias

**Comment by psytester** [comment]
That was a fast reply :-) Then I will wait for the Gplot support.

**Comment by psytester** [comment]
New andFhem version works great. I see my SVG definitions as in Web-IF of fhem and overview of Hooks is already update... (http://andfhem.klass.li/hooks.html)
You can close this issue, if there is no other work on it from your side.

**Comment by klassm** [comment]
OK thanks!
