### ISSUE TITLE
HM Sec-SC not visible

### ISSUE THREAD

**Issue by dklueh79** [klassm/andFHEM#922]
Since  last update hm sec-sco door and window sensors a status couldn't be seen anymore. Even in details. Presence isn't displayed either. 
HTC ONE m8
![screenshot_2015-05-24-23-11-09](https://cloud.githubusercontent.com/assets/6195999/7789704/689f3a88-026a-11e5-8f75-82dd45e36777.png)

**Comment by klassm** [comment]
Sorry, I'll fix that tomorrow ...
Am 24.05.2015 11:10 nachm. schrieb "dklueh79" <notifications@github.com>:

**Comment by dklueh79** [comment]
Great, thx
