### ISSUE TITLE
Extension of the shutter states

### ISSUE THREAD

**Issue by mr-p666** [klassm/andFHEM#928]
Hej Matthias,

could you extend the state behavior of the shutters?
Exactly it's about the slider:
So that the state 'open' and also 'opened' is used to show 0 percent while 'close' and also 'closed' is used to show 100 percent.

Thx a lot! :-)

**Comment by klassm** [comment]
Even if not having tried that explicitly this should work using the next version. If not, feel free to reopen the issue.
