### ISSUE TITLE
Temperature Sensor: Temperature/Humidity Plot

### ISSUE THREAD

**Issue by grafenhofer** [klassm/andFHEM#931]
Some time ago, the function to plot a temperature/humidity graph for my homematic temp sensor (
HM-WDS40-TH-I-2) vanished from the user interface. It would be great to have that functionality back!

Additional information: I am using the premium version from the google app store. The problem persisted after a reinstall of the app. It affects all my android devices (two tablet + two phones) from different manufacturers (Android 4.4 up to 5.1).

**Comment by klassm** [comment]
Hi,
andFHEM uses by now the SVG devices from FHEM to determine whether and
which graph to show. Please make sure you have defined an SVG device within
FHEM - the respective graph should magically show up in andFHEM.
Matthias
Am 17.06.2015 9:51 vorm. schrieb "grafenhofer" <notifications@github.com>:
