### ISSUE TITLE
"Ok, Google" problem with devices with more than one word

### ISSUE THREAD

**Issue by mr-p666** [klassm/andFHEM#946]
Hej Matthias,

I tried your Google Now integration and recognized that only one worded devices names works.
Because I have more than twenty devices the most of them have two worded device names.
Would be great, if you can fix this.
Another thing - but want to avoid to open another issue - can you also add voice commands for shutters? So it's possible to say something like "Open shutter bedroom" or "Öffne Rollo Schlafzimmer".

Thx a lot! :-)

**Comment by klassm** [comment]
Hi,

jip that's a nice requirement. However, I won't solve that too soon, as I am still working on migrating all those different devices to be handled in a generic way.... this takes some time ...

Matthias

**Comment by klassm** [comment]
oh btw: Open as keyword or (öffne) will never work, as this is a reserved keyword in google now for opening apps :-(

**Comment by klassm** [comment]
I've added that feature for the next version. However, this _only_ works using the pronunication hook. If this hook contains words with whitespaces, andFHEM will also match those devices.
