### ISSUE TITLE
Slider-Problem

### ISSUE THREAD

**Issue by martin9959** [klassm/andFHEM#950]
Hallo Matthias,

das: 

define soll_aktuell dummy
attr soll_aktuell setList state:slider,10,1,30
attr soll_aktuell webCmd state
 
hat bis ca. Version 3.4.8 problemlos funktioniert - in der Übersicht erschien ein Slider, den ich ziehen und so Werte zwischen 10 und 30 setzen konnte. Jetzt (3.8.1) nimmt soll_aktuell beim Verschieben des Sliders in der Übersicht von andFHEM den Wert "state xx" an (also z.B. "state 25" und nicht nur die Zahl "25"). 

Wenn ich in andFHEM die Details von soll_aktuell ansehe, erscheint ebenfalls ein Slider (allerdings mit Werten zwischen 0 und 20!) - wenn ich diesen ziehe, bleibt andFHEM hängen (Android teilt mit, dass diese App nicht mehr reagiert und biete an, sie zu schließen). Nur die "Dim +" und "Dim -"-Buttons funktionieren wie gewünscht. 

Gruß,

Martin

**Comment by klassm** [comment]
Danke für den Hinweis. Ab der nächsten Version geht das wieder. Das sind eben die Kinderkrankheiten wenn man so viel auf einmal ändert ... Release gibt es noch am Wochenende.
Sorry!
Matthias

**Comment by martin9959** [comment]
Danke für die schnelle Reaktion! Das zweite Problem (Slider in den Details) ist mit Version 3.8.2 gelöst, aber ein Verschieben des Sliders in der Übersicht führt noch immer dazu, dass der Wert "state xx" gesetzt wird, statt "xx".

**Comment by klassm** [comment]
Immer wieder eine Ehre - jeder Wert wird mit "set state $key value" gesetzt. Ausnahme: state selber ...

Naja, das funktioniert dann mit der nächsten Version ...
